"""Canonical semantics for the native-CNOT Gate-2 compiler extension.

Compiler images are recognized structurally before the accepted finite-carrier
selector is consulted.  Their certificate is generated by the cap-free SSA
algorithm and admitted by the unbounded physical refinement theorem.  Every
other term retains Gate 1's validated admission or exact conservative-history
fallback.
"""

from dataclasses import dataclass

from dw import ZERO
from dw_machine import edge_coefficient
from readback import nf_init
from readback_certify import Admission
import semantics as gate1_semantics

import gate2_cnot_shadow as shadow
from gate2_compiler import (Compiled, compile_circuit,
                            compiler_certificate, recognize_compiled)
@dataclass(frozen=True)
class StructuralAdmission:
    term: object
    circuit: object
    certificate_items: tuple

    def certificate(self):
        return dict(self.certificate_items)


@dataclass(frozen=True)
class Sector:
    term: object
    admission: object


Conservative = gate1_semantics.Conservative
halt_mass = gate1_semantics.halt_mass
error_mass = gate1_semantics.error_mass
running_mass = gate1_semantics.running_mass
rho = gate1_semantics.rho
dyadic_weight = gate1_semantics.dyadic_weight


def _compiled_metadata(term, circuit):
    canonical = compile_circuit(circuit)
    # Recognition permits only reordering independent unary gates between two
    # synchronization boundaries.  Path metadata must be derived from the
    # actual source term rather than from the canonical reordered rendering.
    from gate2_compiler import _walk
    from lam_iam import Var, binder_path
    c_binder = tuple("fffbb")
    occurrences = tuple(
        path for path, node in _walk(term)
        if isinstance(node, Var) and binder_path(term, path) == c_binder)
    prep = occurrences[:circuit.width]
    if len(prep) != circuit.width:
        raise ValueError("recognized compiler term lost preparation prefix")
    boundary = prep[-1][:-3] + ("a",)
    return Compiled(circuit, term, prep, boundary)


def select(term):
    """Total selection with cap-free structural compiler admission.

    Recognition and certificate construction are finite syntax walks.  A
    recognized compiler image is admitted directly; it never enters Gate 1's
    bounded discovery or the historical finite-carrier validator.  Malformed
    or noncompiler terms retain Gate 1's validated/fallback semantics.
    """
    try:
        circuit = recognize_compiled(term)
        if circuit is not None:
            compiled = _compiled_metadata(term, circuit)
            certificate = compiler_certificate(compiled)
            return Sector(term, StructuralAdmission(
                term, circuit,
                tuple(sorted(certificate.items(), key=repr))))
    except (AssertionError, RecursionError, RuntimeError, TypeError,
            ValueError):
        pass
    accepted = gate1_semantics.select(term)
    return Sector(term, accepted.admission)


def _require(sector):
    if not isinstance(sector, Sector):
        raise TypeError("Gate-2 U requires gate2_semantics.Sector")
    admission = sector.admission
    if admission is None:
        return sector.term, None, True, False
    if not isinstance(admission, (Admission, StructuralAdmission)) \
            or admission.term != sector.term:
        raise TypeError("Gate-2 sector admission mismatch")
    return (sector.term, admission.certificate(), False,
            isinstance(admission, StructuralAdmission))


def U(sector, vector):
    term, certificate, conservative, compiled = _require(sector)
    step = shadow.nf_step if compiled else gate1_semantics.nf_step
    target = {}
    for source, amplitude in vector.items():
        if conservative:
            if not isinstance(source, Conservative):
                raise TypeError("conservative sector has unlogged basis")
            live, history = source.live, source.history
        else:
            if isinstance(source, Conservative):
                raise TypeError("certified sector has conservative basis")
            live, history = source, None
        for sign, denominator, rule, landing in step(term, live, certificate):
            coefficient = edge_coefficient(sign, denominator, rule)
            basis = (Conservative(landing, history + (live,))
                     if conservative else landing)
            target[basis] = (target.get(basis, ZERO)
                             + amplitude * coefficient)
    return {basis: amplitude for basis, amplitude in target.items()
            if amplitude != ZERO}


def evolve(sector, transitions):
    term, _certificate, conservative, _compiled = _require(sector)
    initial = nf_init(term)
    from dw import ONE
    state = {Conservative(initial) if conservative else initial: ONE}
    yield 0, state
    for time in range(1, transitions + 1):
        state = U(sector, state)
        yield time, state


def mu_p(sector, transitions):
    vector = None
    for _time, vector in evolve(sector, transitions):
        pass
    return halt_mass(vector)


def mu_approximants(sector, transitions):
    return [(time, halt_mass(vector))
            for time, vector in evolve(sector, transitions)]


def rho_p(sector, transitions):
    vector = None
    for _time, vector in evolve(sector, transitions):
        pass
    return rho(vector)


def rho_approximants(sector, transitions):
    return [(time, rho(vector))
            for time, vector in evolve(sector, transitions)]


def finite_M(programs, transitions):
    matrix = {}
    omega = ZERO
    for bit_length, sector in programs:
        _require(sector)
        vector = None
        for _time, vector in evolve(sector, transitions):
            pass
        weight = dyadic_weight(bit_length)
        omega += weight * halt_mass(vector)
        for coordinate, value in rho(vector).items():
            matrix[coordinate] = matrix.get(coordinate, ZERO) + weight * value
    return ({coordinate: value for coordinate, value in matrix.items()
             if value != ZERO}, omega)
