import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_832 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_833 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_834 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_835 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_836 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn], direction := .down, log := [], tape := [.bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_837 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_838 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_839 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_840 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_841 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_842 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_843 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_844 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_845 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn], direction := .down, log := [], tape := [.bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_846 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_847 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_848 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_849 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_850 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_851 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_852 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_853 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_854 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_855 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_856 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn], direction := .down, log := [], tape := [.bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_857 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_858 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_859 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_860 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_861 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_862 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_863 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_26 : List State := [
  state_832,
  state_833,
  state_834,
  state_835,
  state_836,
  state_837,
  state_838,
  state_839,
  state_840,
  state_841,
  state_842,
  state_843,
  state_844,
  state_845,
  state_846,
  state_847,
  state_848,
  state_849,
  state_850,
  state_851,
  state_852,
  state_853,
  state_854,
  state_855,
  state_856,
  state_857,
  state_858,
  state_859,
  state_860,
  state_861,
  state_862,
  state_863,
]
def index_26 : List StateSlot := [
  ⟨9886918085964742267, state_832⟩,
  ⟨2770560388508690465, state_833⟩,
  ⟨16116410153240898663, state_834⟩,
  ⟨6944133887623516355, state_835⟩,
  ⟨10871781141588584081, state_836⟩,
  ⟨15611253439616240435, state_837⟩,
  ⟨8362304212796313041, state_838⟩,
  ⟨18298543713842465069, state_839⟩,
  ⟨14252052132398800651, state_840⟩,
  ⟨14249070827055286621, state_841⟩,
  ⟨339700431006260893, state_842⟩,
  ⟨1136354333495649821, state_843⟩,
  ⟨11508485881417755841, state_844⟩,
  ⟨11244208441972729783, state_845⟩,
  ⟨10931088596337651201, state_846⟩,
  ⟨4602609588026215115, state_847⟩,
  ⟨18366852223038910425, state_848⟩,
  ⟨15154372021729176881, state_849⟩,
  ⟨14002226497764302911, state_850⟩,
  ⟨15026749879945714583, state_851⟩,
  ⟨17774422931540095057, state_852⟩,
  ⟨17348893618536930307, state_853⟩,
  ⟨13861512991755769105, state_854⟩,
  ⟨1281367438957367655, state_855⟩,
  ⟨14382676143324043497, state_856⟩,
  ⟨1049309909541731071, state_857⟩,
  ⟨8722740249074480445, state_858⟩,
  ⟨2387776564271003813, state_859⟩,
  ⟨17139912561815680559, state_860⟩,
  ⟨11058113127559903527, state_861⟩,
  ⟨6510410438664169921, state_862⟩,
  ⟨17190555471350008411, state_863⟩,
]
end p_qq
end QalcCanonicalRRI
