import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_1056 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1057 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1058 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .arg], direction := .up, log := [.alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh))], tape := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1059 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .arg], direction := .up, log := [.alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh))], tape := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1060 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1061 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1062 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) false (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1063 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) false (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1064 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1065 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1066 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn], direction := .down, log := [], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1067 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn], direction := .down, log := [], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1068 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1069 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1070 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1071 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1072 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1073 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1074 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1075 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1076 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1077 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1078 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1079 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1080 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1081 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1082 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1083 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .down, log := [], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1084 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1085 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1086 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1087 : State := .run ({ path := [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn], direction := .up, log := [], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_33 : List State := [
  state_1056,
  state_1057,
  state_1058,
  state_1059,
  state_1060,
  state_1061,
  state_1062,
  state_1063,
  state_1064,
  state_1065,
  state_1066,
  state_1067,
  state_1068,
  state_1069,
  state_1070,
  state_1071,
  state_1072,
  state_1073,
  state_1074,
  state_1075,
  state_1076,
  state_1077,
  state_1078,
  state_1079,
  state_1080,
  state_1081,
  state_1082,
  state_1083,
  state_1084,
  state_1085,
  state_1086,
  state_1087,
]
def index_33 : List StateSlot := [
  ⟨10398713279740935765, state_1056⟩,
  ⟨3701033604102332563, state_1057⟩,
  ⟨16641096829469733083, state_1058⟩,
  ⟨9943417153831129881, state_1059⟩,
  ⟨12543181197269201155, state_1060⟩,
  ⟨13286132164854671253, state_1061⟩,
  ⟨2759966633887746347, state_1062⟩,
  ⟨3502917601473216445, state_1063⟩,
  ⟨13482984150269797603, state_1064⟩,
  ⟨6785304474631194401, state_1065⟩,
  ⟨17893106087561403121, state_1066⟩,
  ⟨11195426411922799919, state_1067⟩,
  ⟨11725854947010944509, state_1068⟩,
  ⟨12468805914596414607, state_1069⟩,
  ⟨2941304489919773033, state_1070⟩,
  ⟨3684255457505243131, state_1071⟩,
  ⟨11781136720443960713, state_1072⟩,
  ⟨5083457044805357511, state_1073⟩,
  ⟨5551047190416052029, state_1074⟩,
  ⟨17300111588487000443, state_1075⟩,
  ⟨10820553752337054249, state_1076⟩,
  ⟨11563504719922524347, state_1077⟩,
  ⟨6025575360448634871, state_1078⟩,
  ⟨6768526328034104969, state_1079⟩,
  ⟨18071917211420987493, state_1080⟩,
  ⟨11374237535782384291, state_1081⟩,
  ⟨17707010773148576865, state_1082⟩,
  ⟨11009331097509973663, state_1083⟩,
  ⟨17788787387500009709, state_1084⟩,
  ⟨84994281375928191, state_1085⟩,
  ⟨4323727930622797981, state_1086⟩,
  ⟨5066678898208268079, state_1087⟩,
]
end p_qq
end QalcCanonicalRRI
