import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_1280 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1281 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1282 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .arg], direction := .up, log := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1283 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .arg], direction := .up, log := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1284 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1285 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1286 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1287 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1288 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1289 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1290 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1291 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1292 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1293 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1294 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1295 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1296 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1297 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1298 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1299 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1300 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1301 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1302 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1303 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1304 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1305 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1306 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1307 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1308 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.recalledAbsent (.fresh)), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1309 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.recalledAbsent (.fresh)), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1310 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_1311 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))) (.recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_40 : List State := [
  state_1280,
  state_1281,
  state_1282,
  state_1283,
  state_1284,
  state_1285,
  state_1286,
  state_1287,
  state_1288,
  state_1289,
  state_1290,
  state_1291,
  state_1292,
  state_1293,
  state_1294,
  state_1295,
  state_1296,
  state_1297,
  state_1298,
  state_1299,
  state_1300,
  state_1301,
  state_1302,
  state_1303,
  state_1304,
  state_1305,
  state_1306,
  state_1307,
  state_1308,
  state_1309,
  state_1310,
  state_1311,
]
def index_40 : List StateSlot := [
  ⟨17782938858516848571, state_1280⟩,
  ⟨11085259182878245369, state_1281⟩,
  ⟨12023429835736735647, state_1282⟩,
  ⟨5325750160098132445, state_1283⟩,
  ⟨7262214498428841407, state_1284⟩,
  ⟨8005165466014311505, state_1285⟩,
  ⟨1939355395992597981, state_1286⟩,
  ⟨2682306363578068079, state_1287⟩,
  ⟨15756907304596600423, state_1288⟩,
  ⟨9059227628957997221, state_1289⟩,
  ⟨14820790080492697901, state_1290⟩,
  ⟨8123110404854094699, state_1291⟩,
  ⟨5894090179287319633, state_1292⟩,
  ⟨6637041146872789731, state_1293⟩,
  ⟨10078651248986765865, state_1294⟩,
  ⟨10821602216572235963, state_1295⟩,
  ⟨6130614158915352331, state_1296⟩,
  ⟨17879678556986300745, state_1297⟩,
  ⟨6000339152464394377, state_1298⟩,
  ⟨17749403550535342791, state_1299⟩,
  ⟨4807170702410055067, state_1300⟩,
  ⟨5550121669995525165, state_1301⟩,
  ⟨16753186072015625655, state_1302⟩,
  ⟨17496137039601095753, state_1303⟩,
  ⟨4247492042558781911, state_1304⟩,
  ⟨15996556440629730325, state_1305⟩,
  ⟨8026370706384642525, state_1306⟩,
  ⟨1328691030746039323, state_1307⟩,
  ⟨16774481078487413615, state_1308⟩,
  ⟨10959314678058440401, state_1309⟩,
  ⟨1126231625015517333, state_1310⟩,
  ⟨1869182592600987431, state_1311⟩,
]
end p_qq
end QalcCanonicalRRI
