import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_288 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 0⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_289 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 0⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_290 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .gam .h, .ans .h false, .bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_291 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .gam .h, .ans .h true, .bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_292 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_293 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_294 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_295 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_296 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_297 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_298 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.gam .h, .ans .h false, .bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_299 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.gam .h, .ans .h true, .bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_300 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_301 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_302 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 2⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_303 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 2⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_304 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 2⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_305 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 2⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_306 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 0⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_307 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 0⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_308 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_309 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_310 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_311 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_312 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_313 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_314 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, false, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_315 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .rho], vb := some ⟨.h, true, 1⟩, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_316 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_317 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_318 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) false (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_319 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .bullet, .bullet, .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_9 : List State := [
  state_288,
  state_289,
  state_290,
  state_291,
  state_292,
  state_293,
  state_294,
  state_295,
  state_296,
  state_297,
  state_298,
  state_299,
  state_300,
  state_301,
  state_302,
  state_303,
  state_304,
  state_305,
  state_306,
  state_307,
  state_308,
  state_309,
  state_310,
  state_311,
  state_312,
  state_313,
  state_314,
  state_315,
  state_316,
  state_317,
  state_318,
  state_319,
]
def index_9 : List StateSlot := [
  ⟨2894875013390564828, state_288⟩,
  ⟨2892961863157856138, state_289⟩,
  ⟨11519164776981297363, state_290⟩,
  ⟨7054533963046118545, state_291⟩,
  ⟨9047689393350066631, state_292⟩,
  ⟨374470182967224119, state_293⟩,
  ⟨3761029269660294731, state_294⟩,
  ⟨3759116119427586041, state_295⟩,
  ⟨14556477418827875917, state_296⟩,
  ⟨14554564268595167227, state_297⟩,
  ⟨917422573018721813, state_298⟩,
  ⟨14899535832793094611, state_299⟩,
  ⟨10134600074134305509, state_300⟩,
  ⟨12261600757859243525, state_301⟩,
  ⟨15805500593026249544, state_302⟩,
  ⟨15803587442793540854, state_303⟩,
  ⟨8154204668484279114, state_304⟩,
  ⟨8152291518251570424, state_305⟩,
  ⟨4465838979358162540, state_306⟩,
  ⟨4463925829125453850, state_307⟩,
  ⟨11502733189368852971, state_308⟩,
  ⟨2829513978986010459, state_309⟩,
  ⟨3182432047816857257, state_310⟩,
  ⟨12955956911143566361, state_311⟩,
  ⟨6600852628082937067, state_312⟩,
  ⟨16374377491409646171, state_313⟩,
  ⟨16127441384795473629, state_314⟩,
  ⟨16125528234562764939, state_315⟩,
  ⟨4149719685067801519, state_316⟩,
  ⟨944480911419987771, state_317⟩,
  ⟨10969992040022085691, state_318⟩,
  ⟨9900995755551660839, state_319⟩,
]
end p_qq
end QalcCanonicalRRI
