import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_640 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_641 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_642 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_643 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))) true (.fresh), .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_644 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_645 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_646 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_647 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_648 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_649 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_650 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_651 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_652 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_653 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_654 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_655 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_656 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_657 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_658 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_659 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_660 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_661 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_662 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_663 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_664 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_665 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_666 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_667 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_668 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) false (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_669 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_670 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_671 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_20 : List State := [
  state_640,
  state_641,
  state_642,
  state_643,
  state_644,
  state_645,
  state_646,
  state_647,
  state_648,
  state_649,
  state_650,
  state_651,
  state_652,
  state_653,
  state_654,
  state_655,
  state_656,
  state_657,
  state_658,
  state_659,
  state_660,
  state_661,
  state_662,
  state_663,
  state_664,
  state_665,
  state_666,
  state_667,
  state_668,
  state_669,
  state_670,
  state_671,
]
def index_20 : List StateSlot := [
  ⟨6589963214865614111, state_640⟩,
  ⟨8701919201974165527, state_641⟩,
  ⟨3820714787207486237, state_642⟩,
  ⟨10265263198919638277, state_643⟩,
  ⟨1009864627269607123, state_644⟩,
  ⟨5475705278488009669, state_645⟩,
  ⟨2919004847711998953, state_646⟩,
  ⟨13601060831607289711, state_647⟩,
  ⟨2583058798611998911, state_648⟩,
  ⟨12773470126437910177, state_649⟩,
  ⟨1830009887805420139, state_650⟩,
  ⟨12617737703536754307, state_651⟩,
  ⟨9417418546839550845, state_652⟩,
  ⟨7501736832408257817, state_653⟩,
  ⟨14223978329773786295, state_654⟩,
  ⟨6248047327306238259, state_655⟩,
  ⟨16804167881754833311, state_656⟩,
  ⟨14656592242794480597, state_657⟩,
  ⟨5164473951556189045, state_658⟩,
  ⟨3937461918099320585, state_659⟩,
  ⟨9962284251240855655, state_660⟩,
  ⟨4681956001791840211, state_661⟩,
  ⟨10217073913520171095, state_662⟩,
  ⟨14469802258242184769, state_663⟩,
  ⟨1370300663547774527, state_664⟩,
  ⟨5836141314766177073, state_665⟩,
  ⟨3279440883990166357, state_666⟩,
  ⟨13961496867885457115, state_667⟩,
  ⟨4478720528559682819, state_668⟩,
  ⟨16454156456379506349, state_669⟩,
  ⟨5991438922953453879, state_670⟩,
  ⟨16352924374598755189, state_671⟩,
]
end p_qq
end QalcCanonicalRRI
