import QalcCanonicalSector_p_qq_Core

namespace QalcCanonicalRRI
open QalcConcrete
set_option maxHeartbeats 0
set_option maxRecDepth 100000
namespace p_qq
def state_800 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_801 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_802 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_803 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .arg], direction := .up, log := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_804 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_805 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_806 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_807 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_808 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_809 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_810 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_811 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_812 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_813 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_814 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_815 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_816 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_817 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_818 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_819 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_820 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_821 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_822 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_823 : State := .run ({ path := [.fn, .arg], direction := .down, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_824 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_825 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_826 : State := .run ({ path := [.fn, .fn], direction := .up, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_827 : State := .run ({ path := [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn], direction := .down, log := [.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.bullet, .bullet, .alpha .h (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))) true (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, true, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_828 : State := .run ({ path := [.fn, .fn, .body, .body, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil), .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_829 : State := .run ({ path := [.fn, .fn, .body, .body, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, false, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_830 : State := .run ({ path := [.fn, .fn], direction := .down, log := [], tape := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)), .bullet, .bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, false, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def state_831 : State := .run ({ path := [.fn, .arg], direction := .up, log := [.lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))], tape := [.bullet, .bullet, .bullet, .bullet, .lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .arg, .body, .body] (.nil), .bullet, .bullet, .rho], vb := none, frames := [⟨⟨.h, .lp [.fn, .fn, .body, .body, .fn, .fn, .fn, .fn] (.nil)⟩, false, .recalledAbsent (.fresh)⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .fn, .fn, .fn, .fn] (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil))⟩, true, .recalledPresent (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh))) (.recalledPresent (.recalledAbsent (.fresh)) (.recalledAbsent (.fresh)))⟩, ⟨⟨.h, .lp [.fn, .fn, .body, .body, .arg, .arg, .fn] (.cons (.lp [.fn, .fn, .body, .body, .arg, .fn, .arg, .body, .fn, .fn] (.nil)) (.cons (.lp [.fn, .fn, .body, .body, .fn, .fn, .arg, .body, .fn, .fn] (.nil)) (.nil)))⟩, true, .recalledAbsent (.fresh)⟩], storage := [.bundle [], .bundle [], .bundle []] })
def carrier_25 : List State := [
  state_800,
  state_801,
  state_802,
  state_803,
  state_804,
  state_805,
  state_806,
  state_807,
  state_808,
  state_809,
  state_810,
  state_811,
  state_812,
  state_813,
  state_814,
  state_815,
  state_816,
  state_817,
  state_818,
  state_819,
  state_820,
  state_821,
  state_822,
  state_823,
  state_824,
  state_825,
  state_826,
  state_827,
  state_828,
  state_829,
  state_830,
  state_831,
]
def index_25 : List StateSlot := [
  ⟨17018298108786707853, state_800⟩,
  ⟨246318760826229233, state_801⟩,
  ⟨11551914676559022663, state_802⟩,
  ⟨2172523956680169471, state_803⟩,
  ⟨16877584602778174047, state_804⟩,
  ⟨4947680393547433921, state_805⟩,
  ⟨2825895996726237679, state_806⟩,
  ⟨5525462921978458815, state_807⟩,
  ⟨11738811860096885387, state_808⟩,
  ⟨6054089518861070079, state_809⟩,
  ⟨8621490281140904759, state_810⟩,
  ⟨3660595961178111053, state_811⟩,
  ⟨9526482049686574863, state_812⟩,
  ⟨2410124352230523061, state_813⟩,
  ⟨17404077912636077849, state_814⟩,
  ⟨774661770178182841, state_815⟩,
  ⟨14307596243638223547, state_816⟩,
  ⟨8629358578894448785, state_817⟩,
  ⟨6052705897599566599, state_818⟩,
  ⟨6198152002495021913, state_819⟩,
  ⟨13891616096120633247, state_820⟩,
  ⟨13888634790777119217, state_821⟩,
  ⟨17314723836767561573, state_822⟩,
  ⟨14477882545949707347, state_823⟩,
  ⟨17238020639056341451, state_824⟩,
  ⟨5308116429825601325, state_825⟩,
  ⟨11332200942382414753, state_826⟩,
  ⟨9519394151563869373, state_827⟩,
  ⟨14855957221303451009, state_828⟩,
  ⟨14793935985451009477, state_829⟩,
  ⟨2736533124764695715, state_830⟩,
  ⟨13555029211997463647, state_831⟩,
]
end p_qq
end QalcCanonicalRRI
