/-
Generated by certlean — DO NOT EDIT. 2 RATCHET kill(s) at n=35.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.HeadTower
import Blc.Wire

namespace Blc.Certs

/-- `01000101101010000001011010000110110` (35 bits, RATCHET). -/
def cert_01000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010000110110 : ¬ HasNormalForm (cert_01000101101010000001011010000110110).T :=
  (cert_01000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000101101010000001011010000110110 :
    blcCode (cert_01000101101010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110100001100001010110001011010` (35 bits, RATCHET2). -/
def cert_01000110100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110100001100001010110001011010 : ¬ HasNormalForm (cert_01000110100001100001010110001011010).T :=
  (cert_01000110100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_01000110100001100001010110001011010 :
    blcCode (cert_01000110100001100001010110001011010).T = [false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

end Blc.Certs
