/-
Generated by certlean — DO NOT EDIT. 1 RATCHET kill(s) at n=35.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.Wire

namespace Blc.Certs

/-- `01000101101010000001011010000110110` (35 bits). -/
def cert_01000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010000110110 : ¬ HasNormalForm (cert_01000101101010000001011010000110110).T :=
  (cert_01000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000101101010000001011010000110110 :
    blcCode (cert_01000101101010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

end Blc.Certs
