/-
Generated by `blam cert lean` — DO NOT EDIT. 39 RATCHET kill(s) at n=39.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.HeadTower
import Blc.Selector
import Blc.Rigid
import Blc.Wire

namespace Blc.Certs

/-- `000001000101101010000001011010000110110` (39 bits, RATCHET). -/
def cert_000001000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_000001000101101010000001011010000110110 : ¬ HasNormalForm (cert_000001000101101010000001011010000110110).T :=
  (cert_000001000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_000001000101101010000001011010000110110 :
    blcCode (cert_000001000101101010000001011010000110110).T = [false, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `000001000110100001100001010110001011010` (39 bits, RATCHET2). -/
def cert_000001000110100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.lam (.lam (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := []

theorem kill_000001000110100001100001010110001011010 : ¬ HasNormalForm (cert_000001000110100001100001010110001011010).T :=
  (cert_000001000110100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_000001000110100001100001010110001011010 :
    blcCode (cert_000001000110100001100001010110001011010).T = [false, false, false, false, false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

/-- `000100010110001010000001011010000110110` (39 bits, RATCHET). -/
def cert_000100010110001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_000100010110001010000001011010000110110 : ¬ HasNormalForm (cert_000100010110001010000001011010000110110).T :=
  (cert_000100010110001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_000100010110001010000001011010000110110 :
    blcCode (cert_000100010110001010000001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `000100010110001101100001011010000110110` (39 bits, RATCHET). -/
def cert_000100010110001101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 1))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.var 0)]

theorem kill_000100010110001101100001011010000110110 : ¬ HasNormalForm (cert_000100010110001101100001011010000110110).T :=
  (cert_000100010110001101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_000100010110001101100001011010000110110 :
    blcCode (cert_000100010110001101100001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `000100011100110001100001011010000110110` (39 bits, RATCHET-ARG). -/
def cert_000100011100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 0
  binders := 0
  n0 := 0
  trail := []

def target_000100011100110001100001011010000110110 : Term := (.lam (.app (.lam (.app (.var 1) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))

theorem kill_000100011100110001100001011010000110110 : ¬ HasNormalForm target_000100011100110001100001011010000110110 :=
  argKill (k := 1) (s := (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))) (a := (cert_000100011100110001100001011010000110110).T)
    (by decide) (by decide) (by decide)
    ((cert_000100011100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide)))

theorem wire_000100011100110001100001011010000110110 :
    blcCode target_000100011100110001100001011010000110110 = [false, false, false, true, false, false, false, true, true, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010000010111010110000001011010000110110` (39 bits, RATCHET). -/
def cert_010000010111010110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.var 0)) (.var 1)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_010000010111010110000001011010000110110 : ¬ HasNormalForm (cert_010000010111010110000001011010000110110).T :=
  (cert_010000010111010110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010000010111010110000001011010000110110 :
    blcCode (cert_010000010111010110000001011010000110110).T = [false, true, false, false, false, false, false, true, false, true, true, true, false, true, false, true, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010000011101100001100001010110001011010` (39 bits, RATCHET2). -/
def cert_010000011101100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.app (.lam (.lam (.app (.var 1) (.var 1)))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_010000011101100001100001010110001011010 : ¬ HasNormalForm (cert_010000011101100001100001010110001011010).T :=
  (cert_010000011101100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_010000011101100001100001010110001011010 :
    blcCode (cert_010000011101100001100001010110001011010).T = [false, true, false, false, false, false, false, true, true, true, false, true, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

/-- `010001000110001110100001011010000110110` (39 bits, RATCHET). -/
def cert_010001000110001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 2)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000110001110100001011010000110110 : ¬ HasNormalForm (cert_010001000110001110100001011010000110110).T :=
  (cert_010001000110001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001000110001110100001011010000110110 :
    blcCode (cert_010001000110001110100001011010000110110).T = [false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001000111000110100001011010000110110` (39 bits, RATCHET). -/
def cert_010001000111000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 1) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000111000110100001011010000110110 : ¬ HasNormalForm (cert_010001000111000110100001011010000110110).T :=
  (cert_010001000111000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001000111000110100001011010000110110 :
    blcCode (cert_010001000111000110100001011010000110110).T = [false, true, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001000111010001100001011010000110110` (39 bits, RATCHET). -/
def cert_010001000111010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 1) (.var 0))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000111010001100001011010000110110 : ¬ HasNormalForm (cert_010001000111010001100001011010000110110).T :=
  (cert_010001000111010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001000111010001100001011010000110110 :
    blcCode (cert_010001000111010001100001011010000110110).T = [false, true, false, false, false, true, false, false, false, true, true, true, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001010011010001100001011010000110110` (39 bits, RATCHET). -/
def cert_010001010011010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001010011010001100001011010000110110 : ¬ HasNormalForm (cert_010001010011010001100001011010000110110).T :=
  (cert_010001010011010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001010011010001100001011010000110110 :
    blcCode (cert_010001010011010001100001011010000110110).T = [false, true, false, false, false, true, false, true, false, false, true, true, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001010110101010000001011010000110110` (39 bits, RATCHET). -/
def cert_010001010110101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.var 0) (.var 0)) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_010001010110101010000001011010000110110 : ¬ HasNormalForm (cert_010001010110101010000001011010000110110).T :=
  (cert_010001010110101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001010110101010000001011010000110110 :
    blcCode (cert_010001010110101010000001011010000110110).T = [false, true, false, false, false, true, false, true, false, true, true, false, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001011000001010000001011010000110110` (39 bits, RATCHET). -/
def cert_010001011000001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001011000001010000001011010000110110 : ¬ HasNormalForm (cert_010001011000001010000001011010000110110).T :=
  (cert_010001011000001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001011000001010000001011010000110110 :
    blcCode (cert_010001011000001010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001011000110001100001011010000110110` (39 bits, RATCHET). -/
def cert_010001011000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_010001011000110001100001011010000110110 : ¬ HasNormalForm (cert_010001011000110001100001011010000110110).T :=
  (cert_010001011000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001011000110001100001011010000110110 :
    blcCode (cert_010001011000110001100001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001011001101010000001011010000110110` (39 bits, RATCHET). -/
def cert_010001011001101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.app (.var 0) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001011001101010000001011010000110110 : ¬ HasNormalForm (cert_010001011001101010000001011010000110110).T :=
  (cert_010001011001101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001011001101010000001011010000110110 :
    blcCode (cert_010001011001101010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, true, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001011010100001100001010110001011010` (39 bits, RATCHET2). -/
def cert_010001011010100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))]

theorem kill_010001011010100001100001010110001011010 : ¬ HasNormalForm (cert_010001011010100001100001010110001011010).T :=
  (cert_010001011010100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_010001011010100001100001010110001011010 :
    blcCode (cert_010001011010100001100001010110001011010).T = [false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

/-- `010001100000011110000110110000101101010` (39 bits, RATCHET). -/
def cert_010001100000011110000110110000101101010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.lam (.app (.var 0) (.var 1)))))))) (.lam (.app (.app (.var 0) (.var 0)) (.var 0))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100000011110000110110000101101010 : ¬ HasNormalForm (cert_010001100000011110000110110000101101010).T :=
  (cert_010001100000011110000110110000101101010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100000011110000110110000101101010 :
    blcCode (cert_010001100000011110000110110000101101010).T = [false, true, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, false, false, false, true, true, false, true, true, false, false, false, false, true, false, true, true, false, true, false, true, false] := by decide

/-- `010001100000011110100001011010000110110` (39 bits, RATCHET). -/
def cert_010001100000011110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))))
  kO := 2
  kD := 2
  kB := 3
  T := (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.var 0)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100000011110100001011010000110110 : ¬ HasNormalForm (cert_010001100000011110100001011010000110110).T :=
  (cert_010001100000011110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100000011110100001011010000110110 :
    blcCode (cert_010001100000011110100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, false, false, true, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100001001110100001011010000110110` (39 bits, RATCHET). -/
def cert_010001100001001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0)))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 2)) (.var 0))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100001001110100001011010000110110 : ¬ HasNormalForm (cert_010001100001001110100001011010000110110).T :=
  (cert_010001100001001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100001001110100001011010000110110 :
    blcCode (cert_010001100001001110100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, true, false, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100001100011100001011010000110110` (39 bits, RATCHET). -/
def cert_010001100001100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kO := 1
  kD := 2
  kB := 3
  T := (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.lam (.var 2)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100001100011100001011010000110110 : ¬ HasNormalForm (cert_010001100001100011100001011010000110110).T :=
  (cert_010001100001100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100001100011100001011010000110110 :
    blcCode (cert_010001100001100011100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, true, true, false, false, false, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100011000010001011010000110111010` (39 bits, RATCHET). -/
def cert_010001100011000010001011010000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011010000110111010 : ¬ HasNormalForm (cert_010001100011000010001011010000110111010).T :=
  (cert_010001100011000010001011010000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010001011010000110111010 :
    blcCode (cert_010001100011000010001011010000110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, true, false, true, false] := by decide

/-- `010001100011000010001011011000011011010` (39 bits, RATCHET). -/
def cert_010001100011000010001011011000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011011000011011010 : ¬ HasNormalForm (cert_010001100011000010001011011000011011010).T :=
  (cert_010001100011000010001011011000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010001011011000011011010 :
    blcCode (cert_010001100011000010001011011000011011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `010001100011000010001011011010000110110` (39 bits, RATCHET). -/
def cert_010001100011000010001011011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 3
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011011010000110110 : ¬ HasNormalForm (cert_010001100011000010001011011010000110110).T :=
  (cert_010001100011000010001011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010001011011010000110110 :
    blcCode (cert_010001100011000010001011011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100011000010001011101000011011010` (39 bits, RATCHET). -/
def cert_010001100011000010001011101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011101000011011010 : ¬ HasNormalForm (cert_010001100011000010001011101000011011010).T :=
  (cert_010001100011000010001011101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010001011101000011011010 :
    blcCode (cert_010001100011000010001011101000011011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `010001100011000010001100001101110011010` (39 bits, RATCHET). -/
def cert_010001100011000010001100001101110011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0)))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0)))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001100001101110011010 : ¬ HasNormalForm (cert_010001100011000010001100001101110011010).T :=
  (cert_010001100011000010001100001101110011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010001100001101110011010 :
    blcCode (cert_010001100011000010001100001101110011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, true, false, false, false, false, true, true, false, true, true, true, false, false, true, true, false, true, false] := by decide

/-- `010001100011000010100011011010000110110` (39 bits, RATCHET). -/
def cert_010001100011000010100011011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010100011011010000110110 : ¬ HasNormalForm (cert_010001100011000010100011011010000110110).T :=
  (cert_010001100011000010100011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010100011011010000110110 :
    blcCode (cert_010001100011000010100011011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100011000010100011101010000110110` (39 bits, RATCHET). -/
def cert_010001100011000010100011101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010100011101010000110110 : ¬ HasNormalForm (cert_010001100011000010100011101010000110110).T :=
  (cert_010001100011000010100011101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010100011101010000110110 :
    blcCode (cert_010001100011000010100011101010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100011000010101001101010000110110` (39 bits, RATCHET). -/
def cert_010001100011000010101001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010101001101010000110110 : ¬ HasNormalForm (cert_010001100011000010101001101010000110110).T :=
  (cert_010001100011000010101001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010101001101010000110110 :
    blcCode (cert_010001100011000010101001101010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, true, false, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100011000010110100001000110111010` (39 bits, RATCHET). -/
def cert_010001100011000010110100001000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0)))))
  W := (.lam (.app (.lam (.app (.var 0) (.mvar 0))) (.var 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001000110111010 : ¬ HasNormalForm (cert_010001100011000010110100001000110111010).T :=
  (cert_010001100011000010110100001000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010110100001000110111010 :
    blcCode (cert_010001100011000010110100001000110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, false, false, true, true, false, true, true, true, false, true, false] := by decide

/-- `010001100011000010110100001000111010110` (39 bits, RATCHET). -/
def cert_010001100011000010110100001000111010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1)))))
  W := (.lam (.app (.lam (.app (.var 1) (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001000111010110 : ¬ HasNormalForm (cert_010001100011000010110100001000111010110).T :=
  (cert_010001100011000010110100001000111010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010110100001000111010110 :
    blcCode (cert_010001100011000010110100001000111010110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, false, false, true, true, true, false, true, false, true, true, false] := by decide

/-- `010001100011000010110100001010011010110` (39 bits, RATCHET). -/
def cert_010001100011000010110100001010011010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001010011010110 : ¬ HasNormalForm (cert_010001100011000010110100001010011010110).T :=
  (cert_010001100011000010110100001010011010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010110100001010011010110 :
    blcCode (cert_010001100011000010110100001010011010110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, false, false, true, true, false, true, false, true, true, false] := by decide

/-- `010001100011000010110100001100001101110` (39 bits, RATCHET). -/
def cert_010001100011000010110100001100001101110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2)))))))
  W := (.lam (.app (.var 0) (.lam (.app (.var 0) (.mvar 0)))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001100001101110 : ¬ HasNormalForm (cert_010001100011000010110100001100001101110).T :=
  (cert_010001100011000010110100001100001101110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010110100001100001101110 :
    blcCode (cert_010001100011000010110100001100001101110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, true, false, true, true, true, false] := by decide

/-- `010001100011000010110100100000110111010` (39 bits, RATCHET). -/
def cert_010001100011000010110100100000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.mvar 0)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0)))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100100000110111010 : ¬ HasNormalForm (cert_010001100011000010110100100000110111010).T :=
  (cert_010001100011000010110100100000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100011000010110100100000110111010 :
    blcCode (cert_010001100011000010110100100000110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, true, false, false, false, false, false, true, true, false, true, true, true, false, true, false] := by decide

/-- `010001100100001110100001011010000110110` (39 bits, RATCHET). -/
def cert_010001100100001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 2))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100100001110100001011010000110110 : ¬ HasNormalForm (cert_010001100100001110100001011010000110110).T :=
  (cert_010001100100001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_010001100100001110100001011010000110110 :
    blcCode (cert_010001100100001110100001011010000110110).T = [false, true, false, false, false, true, true, false, false, true, false, false, false, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `010001100110100001100001010110001011010` (39 bits, RATCHET2). -/
def cert_010001100110100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.app (.lam (.app (.var 0) (.app (.var 0) (.var 0)))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.app (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0))))))) (.var 0)))]

theorem kill_010001100110100001100001010110001011010 : ¬ HasNormalForm (cert_010001100110100001100001010110001011010).T :=
  (cert_010001100110100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_010001100110100001100001010110001011010 :
    blcCode (cert_010001100110100001100001010110001011010).T = [false, true, false, false, false, true, true, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

/-- `000001000110100001100001011000001111010` (39 bits, SELECTOR). -/
def cert_000001000110100001100001011000001111010 : SelCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.mvar 0)))) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  P := (.lam (.lam (.mvar 0)))
  kO := 1
  kF := 1
  kSel := 3
  kB := 0
  T := (.lam (.lam (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := []

theorem kill_000001000110100001100001011000001111010 : ¬ HasNormalForm (cert_000001000110100001100001011000001111010).T :=
  (cert_000001000110100001100001011000001111010).noNormalForm (SelCert.valid_of_check (by decide))

theorem wire_000001000110100001100001011000001111010 :
    blcCode (cert_000001000110100001100001011000001111010).T = [false, false, false, false, false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, true, true, true, false, true, false] := by decide

/-- `010000011101100001100001011000001111010` (39 bits, SELECTOR). -/
def cert_010000011101100001100001011000001111010 : SelCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.mvar 0)))) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  P := (.lam (.lam (.mvar 0)))
  kO := 1
  kF := 1
  kSel := 3
  kB := 0
  T := (.app (.lam (.lam (.app (.var 1) (.var 1)))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_010000011101100001100001011000001111010 : ¬ HasNormalForm (cert_010000011101100001100001011000001111010).T :=
  (cert_010000011101100001100001011000001111010).noNormalForm (SelCert.valid_of_check (by decide))

theorem wire_010000011101100001100001011000001111010 :
    blcCode (cert_010000011101100001100001011000001111010).T = [false, true, false, false, false, false, false, true, true, true, false, true, true, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, true, true, true, false, true, false] := by decide

/-- `010001011010100001100001011000001111010` (39 bits, SELECTOR). -/
def cert_010001011010100001100001011000001111010 : SelCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.mvar 0)))) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  P := (.lam (.lam (.mvar 0)))
  kO := 1
  kF := 1
  kSel := 3
  kB := 0
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))]

theorem kill_010001011010100001100001011000001111010 : ¬ HasNormalForm (cert_010001011010100001100001011000001111010).T :=
  (cert_010001011010100001100001011000001111010).noNormalForm (SelCert.valid_of_check (by decide))

theorem wire_010001011010100001100001011000001111010 :
    blcCode (cert_010001011010100001100001011000001111010).T = [false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, true, true, true, false, true, false] := by decide

/-- `010001100110100001100001011000001111010` (39 bits, SELECTOR). -/
def cert_010001100110100001100001011000001111010 : SelCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.mvar 0)))) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  P := (.lam (.lam (.mvar 0)))
  kO := 1
  kF := 1
  kSel := 3
  kB := 0
  T := (.app (.lam (.app (.var 0) (.app (.var 0) (.var 0)))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0))))))))) (.var 0)))]

theorem kill_010001100110100001100001011000001111010 : ¬ HasNormalForm (cert_010001100110100001100001011000001111010).T :=
  (cert_010001100110100001100001011000001111010).noNormalForm (SelCert.valid_of_check (by decide))

theorem wire_010001100110100001100001011000001111010 :
    blcCode (cert_010001100110100001100001011000001111010).T = [false, true, false, false, false, true, true, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, true, true, true, false, true, false] := by decide

end Blc.Certs
