/-
Generated by certlean — DO NOT EDIT. 4 RATCHET kill(s) at n=36.
Every obligation is replayed by the Lean kernel (`by decide`).
-/
import Blc.Ratchet

namespace Blc.Certs

/-- `000001000110001100001011010000110110` (36 bits). -/
def cert_000001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := []

theorem kill_000001000110001100001011010000110110 : ¬ HasNormalForm (cert_000001000110001100001011010000110110).T :=
  (cert_000001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010000011100011100001011010000110110` (36 bits). -/
def cert_010000011100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.var 1) (.lam (.var 2))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_010000011100011100001011010000110110 : ¬ HasNormalForm (cert_010000011100011100001011010000110110).T :=
  (cert_010000011100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001011000110100001011010000110110` (36 bits). -/
def cert_010001011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_010001011000110100001011010000110110 : ¬ HasNormalForm (cert_010001011000110100001011010000110110).T :=
  (cert_010001011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100110001100001011010000110110` (36 bits). -/
def cert_010001100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))]

theorem kill_010001100110001100001011010000110110 : ¬ HasNormalForm (cert_010001100110001100001011010000110110).T :=
  (cert_010001100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

end Blc.Certs
