/-
Generated by certlean — DO NOT EDIT. 30 RATCHET kill(s) at n=38.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.HeadTower
import Blc.Selector
import Blc.Wire

namespace Blc.Certs

/-- `00000001000110001100001011010000110110` (38 bits, RATCHET). -/
def cert_00000001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 1
  binders := 3
  n0 := 0
  trail := []

theorem kill_00000001000110001100001011010000110110 : ¬ HasNormalForm (cert_00000001000110001100001011010000110110).T :=
  (cert_00000001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00000001000110001100001011010000110110 :
    blcCode (cert_00000001000110001100001011010000110110).T = [false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `00010000011100011100001011010000110110` (38 bits, RATCHET). -/
def cert_00010000011100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.lam (.app (.var 1) (.lam (.var 2))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := []

theorem kill_00010000011100011100001011010000110110 : ¬ HasNormalForm (cert_00010000011100011100001011010000110110).T :=
  (cert_00010000011100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00010000011100011100001011010000110110 :
    blcCode (cert_00010000011100011100001011010000110110).T = [false, false, false, true, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `00010001011000110100001011010000110110` (38 bits, RATCHET). -/
def cert_00010001011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_00010001011000110100001011010000110110 : ¬ HasNormalForm (cert_00010001011000110100001011010000110110).T :=
  (cert_00010001011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00010001011000110100001011010000110110 :
    blcCode (cert_00010001011000110100001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `00010001011011010000001011010000110110` (38 bits, RATCHET). -/
def cert_00010001011011010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001011011010000001011010000110110 : ¬ HasNormalForm (cert_00010001011011010000001011010000110110).T :=
  (cert_00010001011011010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00010001011011010000001011010000110110 :
    blcCode (cert_00010001011011010000001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `00010001100110001100001011010000110110` (38 bits, RATCHET). -/
def cert_00010001100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))]

theorem kill_00010001100110001100001011010000110110 : ¬ HasNormalForm (cert_00010001100110001100001011010000110110).T :=
  (cert_00010001100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00010001100110001100001011010000110110 :
    blcCode (cert_00010001100110001100001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `00010100011000110000101101000011011010` (38 bits, RATCHET). -/
def cert_00010100011000110000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0)))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.var 0)]

theorem kill_00010100011000110000101101000011011010 : ¬ HasNormalForm (cert_00010100011000110000101101000011011010).T :=
  (cert_00010100011000110000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_00010100011000110000101101000011011010 :
    blcCode (cert_00010100011000110000101101000011011010).T = [false, false, false, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `01000100011000110100001011010000110110` (38 bits, RATCHET). -/
def cert_01000100011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000100011000110100001011010000110110 : ¬ HasNormalForm (cert_01000100011000110100001011010000110110).T :=
  (cert_01000100011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000100011000110100001011010000110110 :
    blcCode (cert_01000100011000110100001011010000110110).T = [false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000100100110001100001011010000110110` (38 bits, RATCHET). -/
def cert_01000100100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.var 0)) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000100100110001100001011010000110110 : ¬ HasNormalForm (cert_01000100100110001100001011010000110110).T :=
  (cert_01000100100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000100100110001100001011010000110110 :
    blcCode (cert_01000100100110001100001011010000110110).T = [false, true, false, false, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000101001010001100001011010000110110` (38 bits, RATCHET). -/
def cert_01000101001010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101001010001100001011010000110110 : ¬ HasNormalForm (cert_01000101001010001100001011010000110110).T :=
  (cert_01000101001010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000101001010001100001011010000110110 :
    blcCode (cert_01000101001010001100001011010000110110).T = [false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000101100011000100001011010000110110` (38 bits, RATCHET). -/
def cert_01000101100011000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_01000101100011000100001011010000110110 : ¬ HasNormalForm (cert_01000101100011000100001011010000110110).T :=
  (cert_01000101100011000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000101100011000100001011010000110110 :
    blcCode (cert_01000101100011000100001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000101100011010000001011010000110110` (38 bits, RATCHET). -/
def cert_01000101100011010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100011010000001011010000110110 : ¬ HasNormalForm (cert_01000101100011010000001011010000110110).T :=
  (cert_01000101100011010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000101100011010000001011010000110110 :
    blcCode (cert_01000101100011010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110000100101100001011010000110110` (38 bits, RATCHET). -/
def cert_01000110000100101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 0)) (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110000100101100001011010000110110 : ¬ HasNormalForm (cert_01000110000100101100001011010000110110).T :=
  (cert_01000110000100101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110000100101100001011010000110110 :
    blcCode (cert_01000110000100101100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, true, false, false, true, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110000101101000011011000011000110` (38 bits, RATCHET). -/
def cert_01000110000101101000011011000011000110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.var 0) (.lam (.var 1)))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110000101101000011011000011000110 : ¬ HasNormalForm (cert_01000110000101101000011011000011000110).T :=
  (cert_01000110000101101000011011000011000110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110000101101000011011000011000110 :
    blcCode (cert_01000110000101101000011011000011000110).T = [false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, false, true, true, false, false, false, true, true, false] := by decide

/-- `01000110001100001000101101000011011010` (38 bits, RATCHET). -/
def cert_01000110001100001000101101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001000101101000011011010 : ¬ HasNormalForm (cert_01000110001100001000101101000011011010).T :=
  (cert_01000110001100001000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001000101101000011011010 :
    blcCode (cert_01000110001100001000101101000011011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `01000110001100001000101101010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001000101101010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001000101101010000110110 : ¬ HasNormalForm (cert_01000110001100001000101101010000110110).T :=
  (cert_01000110001100001000101101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001000101101010000110110 :
    blcCode (cert_01000110001100001000101101010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001001001011010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001001001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001001001011010000110110 : ¬ HasNormalForm (cert_01000110001100001001001011010000110110).T :=
  (cert_01000110001100001001001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001001001011010000110110 :
    blcCode (cert_01000110001100001001001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, true, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001010001101010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001010001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001010001101010000110110 : ¬ HasNormalForm (cert_01000110001100001010001101010000110110).T :=
  (cert_01000110001100001010001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001010001101010000110110 :
    blcCode (cert_01000110001100001010001101010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001010010011010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001010010011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001010010011010000110110 : ¬ HasNormalForm (cert_01000110001100001010010011010000110110).T :=
  (cert_01000110001100001010010011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001010010011010000110110 :
    blcCode (cert_01000110001100001010010011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, true, false, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001010100101010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001010100101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001010100101010000110110 : ¬ HasNormalForm (cert_01000110001100001010100101010000110110).T :=
  (cert_01000110001100001010100101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001010100101010000110110 :
    blcCode (cert_01000110001100001010100101010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, true, false, false, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001011010000100100110110` (38 bits, RATCHET). -/
def cert_01000110001100001011010000100100110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.lam (.var 0)) (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010000100100110110 : ¬ HasNormalForm (cert_01000110001100001011010000100100110110).T :=
  (cert_01000110001100001011010000100100110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001011010000100100110110 :
    blcCode (cert_01000110001100001011010000100100110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, false, true, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100001011010000101001010110` (38 bits, RATCHET). -/
def cert_01000110001100001011010000101001010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010000101001010110 : ¬ HasNormalForm (cert_01000110001100001011010000101001010110).T :=
  (cert_01000110001100001011010000101001010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001011010000101001010110 :
    blcCode (cert_01000110001100001011010000101001010110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, false, false, true, false, true, false, true, true, false] := by decide

/-- `01000110001100001011010000101100010110` (38 bits, RATCHET). -/
def cert_01000110001100001011010000101100010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1)))))
  W := (.lam (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010000101100010110 : ¬ HasNormalForm (cert_01000110001100001011010000101100010110).T :=
  (cert_01000110001100001011010000101100010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001011010000101100010110 :
    blcCode (cert_01000110001100001011010000101100010110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, true, false, false, false, true, false, true, true, false] := by decide

/-- `01000110001100001011010010000011011010` (38 bits, RATCHET). -/
def cert_01000110001100001011010010000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0)))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010010000011011010 : ¬ HasNormalForm (cert_01000110001100001011010010000011011010).T :=
  (cert_01000110001100001011010010000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001011010010000011011010 :
    blcCode (cert_01000110001100001011010010000011011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, true, false, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `01000110001100001011010010010000110110` (38 bits, RATCHET). -/
def cert_01000110001100001011010010010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.app (.lam (.var 0)) (.lam (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010010010000110110 : ¬ HasNormalForm (cert_01000110001100001011010010010000110110).T :=
  (cert_01000110001100001011010010010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100001011010010010000110110 :
    blcCode (cert_01000110001100001011010010010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, true, false, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110001100100100001011010000110110` (38 bits, RATCHET). -/
def cert_01000110001100100100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100100100001011010000110110 : ¬ HasNormalForm (cert_01000110001100100100001011010000110110).T :=
  (cert_01000110001100100100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110001100100100001011010000110110 :
    blcCode (cert_01000110001100100100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, true, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110010000110100001011010000110110` (38 bits, RATCHET). -/
def cert_01000110010000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.var 1))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 1))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110010000110100001011010000110110 : ¬ HasNormalForm (cert_01000110010000110100001011010000110110).T :=
  (cert_01000110010000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110010000110100001011010000110110 :
    blcCode (cert_01000110010000110100001011010000110110).T = [false, true, false, false, false, true, true, false, false, true, false, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01000110010010001100001011010000110110` (38 bits, RATCHET). -/
def cert_01000110010010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.var 0)) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.app (.lam (.var 0)) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110010010001100001011010000110110 : ¬ HasNormalForm (cert_01000110010010001100001011010000110110).T :=
  (cert_01000110010010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01000110010010001100001011010000110110 :
    blcCode (cert_01000110010010001100001011010000110110).T = [false, true, false, false, false, true, true, false, false, true, false, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01001001000110001100001011010000110110` (38 bits, RATCHET). -/
def cert_01001001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.var 0)) (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01001001000110001100001011010000110110 : ¬ HasNormalForm (cert_01001001000110001100001011010000110110).T :=
  (cert_01001001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01001001000110001100001011010000110110 :
    blcCode (cert_01001001000110001100001011010000110110).T = [false, true, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `01010001100011000010110100001101100010` (38 bits, RATCHET). -/
def cert_01010001100011000010110100001101100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 0)))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_01010001100011000010110100001101100010 : ¬ HasNormalForm (cert_01010001100011000010110100001101100010).T :=
  (cert_01010001100011000010110100001101100010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01010001100011000010110100001101100010 :
    blcCode (cert_01010001100011000010110100001101100010).T = [false, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, true, false] := by decide

/-- `01010010000110001100001011010000110110` (38 bits, RATCHET). -/
def cert_01010010000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.var 0)) (.lam (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01010010000110001100001011010000110110 : ¬ HasNormalForm (cert_01010010000110001100001011010000110110).T :=
  (cert_01010010000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_01010010000110001100001011010000110110 :
    blcCode (cert_01010010000110001100001011010000110110).T = [false, true, false, true, false, false, true, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

end Blc.Certs
