/-
Generated by certlean — DO NOT EDIT. 1 RATCHET kill(s) at n=34.
Every obligation is replayed by the Lean kernel (`by decide`).
-/
import Blc.Ratchet

namespace Blc.Certs

/-- `0001000110001100001011010000110110` (34 bits). -/
def cert_0001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010000110110 : ¬ HasNormalForm (cert_0001000110001100001011010000110110).T :=
  (cert_0001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

end Blc.Certs
