/-
Generated by certlean — DO NOT EDIT. 87 RATCHET kill(s) at n=41.
Every obligation is replayed by the Lean kernel (`by decide`).
-/
import Blc.Ratchet

namespace Blc.Certs

/-- `01000101100110001010000001011010000110110` (41 bits). -/
def cert_01000101100110001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.app (.var 0) (.lam (.var 0)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100110001010000001011010000110110 : ¬ HasNormalForm (cert_01000101100110001010000001011010000110110).T :=
  (cert_01000101100110001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01010001100011000010110100001101100000110` (41 bits). -/
def cert_01010001100011000010110100001101100000110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.lam (.var 1))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.var 1)))]

theorem kill_01010001100011000010110100001101100000110 : ¬ HasNormalForm (cert_01010001100011000010110100001101100000110).T :=
  (cert_01010001100011000010110100001101100000110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100000011110100001011010000110110` (41 bits). -/
def cert_00010001100000011110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))))
  kO := 2
  kD := 2
  kB := 3
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.var 0)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100000011110100001011010000110110 : ¬ HasNormalForm (cert_00010001100000011110100001011010000110110).T :=
  (cert_00010001100000011110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100001100011100001011010000110110` (41 bits). -/
def cert_00010001100001100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kO := 1
  kD := 2
  kB := 3
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.lam (.var 2)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100001100011100001011010000110110 : ¬ HasNormalForm (cert_00010001100001100011100001011010000110110).T :=
  (cert_00010001100001100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100001001110100001011010000110110` (41 bits). -/
def cert_00010001100001001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0)))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 2)) (.var 0))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100001001110100001011010000110110 : ¬ HasNormalForm (cert_00010001100001001110100001011010000110110).T :=
  (cert_00010001100001001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100100001110100001011010000110110` (41 bits). -/
def cert_00010001100100001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 2))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100100001110100001011010000110110 : ¬ HasNormalForm (cert_00010001100100001110100001011010000110110).T :=
  (cert_00010001100100001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001000111010001100001011010000110110` (41 bits). -/
def cert_00010001000111010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.app (.var 1) (.var 0))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001000111010001100001011010000110110 : ¬ HasNormalForm (cert_00010001000111010001100001011010000110110).T :=
  (cert_00010001000111010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001011000110001100001011010000110110` (41 bits). -/
def cert_00010001011000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_00010001011000110001100001011010000110110 : ¬ HasNormalForm (cert_00010001011000110001100001011010000110110).T :=
  (cert_00010001011000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001010011010001100001011010000110110` (41 bits). -/
def cert_00010001010011010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001010011010001100001011010000110110 : ¬ HasNormalForm (cert_00010001010011010001100001011010000110110).T :=
  (cert_00010001010011010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001000110001110100001011010000110110` (41 bits). -/
def cert_00010001000110001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 2)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001000110001110100001011010000110110 : ¬ HasNormalForm (cert_00010001000110001110100001011010000110110).T :=
  (cert_00010001000110001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001000111000110100001011010000110110` (41 bits). -/
def cert_00010001000111000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.app (.var 1) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001000111000110100001011010000110110 : ¬ HasNormalForm (cert_00010001000111000110100001011010000110110).T :=
  (cert_00010001000111000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000001110000101101000011011000011000110` (41 bits). -/
def cert_01000001110000101101000011011000011000110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.var 1) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))) (.lam (.app (.var 0) (.lam (.var 1)))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_01000001110000101101000011011000011000110 : ¬ HasNormalForm (cert_01000001110000101101000011011000011000110).T :=
  (cert_01000001110000101101000011011000011000110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101100011000001100001011010000110110` (41 bits). -/
def cert_01000101100011000001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.var 1)))]

theorem kill_01000101100011000001100001011010000110110 : ¬ HasNormalForm (cert_01000101100011000001100001011010000110110).T :=
  (cert_01000101100011000001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000001110011100011100001011010000110110` (41 bits). -/
def cert_01000001110011100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.var 1) (.app (.var 1) (.lam (.var 2)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))]

theorem kill_01000001110011100011100001011010000110110 : ¬ HasNormalForm (cert_01000001110011100011100001011010000110110).T :=
  (cert_01000001110011100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000001000110001101100001011010000110110` (41 bits). -/
def cert_01000001000110001101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_01000001000110001101100001011010000110110 : ¬ HasNormalForm (cert_01000001000110001101100001011010000110110).T :=
  (cert_01000001000110001101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000001011100011101100001011010000110110` (41 bits). -/
def cert_01000001011100011101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.lam (.var 2))) (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_01000001011100011101100001011010000110110 : ¬ HasNormalForm (cert_01000001011100011101100001011010000110110).T :=
  (cert_01000001011100011101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000001011100010110000001011010000110110` (41 bits). -/
def cert_01000001011100010110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.lam (.var 0))) (.var 1)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_01000001011100010110000001011010000110110 : ¬ HasNormalForm (cert_01000001011100010110000001011010000110110).T :=
  (cert_01000001011100010110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010100011000110000101101000011011000110` (41 bits). -/
def cert_00010100011000110000101101000011011000110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 1))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.var 1))]

theorem kill_00010100011000110000101101000011011000110 : ¬ HasNormalForm (cert_00010100011000110000101101000011011000110).T :=
  (cert_00010100011000110000101101000011011000110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000100100101101010000001011010000110110` (41 bits). -/
def cert_01000100100101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.var 0)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000100100101101010000001011010000110110 : ¬ HasNormalForm (cert_01000100100101101010000001011010000110110).T :=
  (cert_01000100100101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101100100101010000001011010000110110` (41 bits). -/
def cert_01000101100100101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.app (.lam (.var 0)) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100100101010000001011010000110110 : ¬ HasNormalForm (cert_01000101100100101010000001011010000110110).T :=
  (cert_01000101100100101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010000010111010110000001011010000110110` (41 bits). -/
def cert_00010000010111010110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.lam (.app (.app (.var 1) (.var 0)) (.var 1)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_00010000010111010110000001011010000110110 : ¬ HasNormalForm (cert_00010000010111010110000001011010000110110).T :=
  (cert_00010000010111010110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110001100001010100110001010000110110` (41 bits). -/
def cert_01000110001100001010100110001010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001010100110001010000110110 : ¬ HasNormalForm (cert_01000110001100001010100110001010000110110).T :=
  (cert_01000110001100001010100110001010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110001100001000101110110000110111010` (41 bits). -/
def cert_01000110001100001000101110110000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001000101110110000110111010 : ¬ HasNormalForm (cert_01000110001100001000101110110000110111010).T :=
  (cert_01000110001100001000101110110000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00000001000101101010000001011010000110110` (41 bits). -/
def cert_00000001000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))))
  kI := 2
  binders := 3
  n0 := 0
  trail := []

theorem kill_00000001000101101010000001011010000110110 : ¬ HasNormalForm (cert_00000001000101101010000001011010000110110).T :=
  (cert_00000001000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01001001000101101010000001011010000110110` (41 bits). -/
def cert_01001001000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.var 0)) (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01001001000101101010000001011010000110110 : ¬ HasNormalForm (cert_01001001000101101010000001011010000110110).T :=
  (cert_01001001000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000100010110101010000001011010000110110` (41 bits). -/
def cert_01000100010110101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000100010110101010000001011010000110110 : ¬ HasNormalForm (cert_01000100010110101010000001011010000110110).T :=
  (cert_01000100010110101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101100000111010000001011010000110110` (41 bits). -/
def cert_01000101100000111010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.lam (.var 2)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100000111010000001011010000110110 : ¬ HasNormalForm (cert_01000101100000111010000001011010000110110).T :=
  (cert_01000101100000111010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101100000001010000001011010000110110` (41 bits). -/
def cert_01000101100000001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.lam (.lam (.var 0))))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100000001010000001011010000110110 : ¬ HasNormalForm (cert_01000101100000001010000001011010000110110).T :=
  (cert_01000101100000001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000100001100110001100001011010000110110` (41 bits). -/
def cert_01000100001100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.lam (.var 1))) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_01000100001100110001100001011010000110110 : ¬ HasNormalForm (cert_01000100001100110001100001011010000110110).T :=
  (cert_01000100001100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01010010000101101010000001011010000110110` (41 bits). -/
def cert_01010010000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.var 0)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01010010000101101010000001011010000110110 : ¬ HasNormalForm (cert_01010010000101101010000001011010000110110).T :=
  (cert_01010010000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101100001101010000001011010000110110` (41 bits). -/
def cert_01000101100001101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.app (.var 0) (.var 0)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101100001101010000001011010000110110 : ¬ HasNormalForm (cert_01000101100001101010000001011010000110110).T :=
  (cert_01000101100001101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110001100001011010000100011101110110` (41 bits). -/
def cert_01000110001100001011010000100011101110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 1)))))
  W := (.lam (.app (.lam (.app (.var 1) (.mvar 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010000100011101110110 : ¬ HasNormalForm (cert_01000110001100001011010000100011101110110).T :=
  (cert_01000110001100001011010000100011101110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110001100001011010000101001100010110` (41 bits). -/
def cert_01000110001100001011010000101001100010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010000101001100010110 : ¬ HasNormalForm (cert_01000110001100001011010000101001100010110).T :=
  (cert_01000110001100001011010000101001100010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001000101101000011011010` (41 bits). -/
def cert_01000101101010000001000101101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001000101101000011011010 : ¬ HasNormalForm (cert_01000101101010000001000101101000011011010).T :=
  (cert_01000101101010000001000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110001100001011010010000011011100010` (41 bits). -/
def cert_01000110001100001011010010000011011100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.lam (.var 0)))))
  W := (.app (.lam (.lam (.app (.var 0) (.mvar 0)))) (.lam (.var 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.lam (.var 0))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.lam (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110001100001011010010000011011100010 : ¬ HasNormalForm (cert_01000110001100001011010010000011011100010).T :=
  (cert_01000110001100001011010010000011011100010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101000110101010000001011010000110110` (41 bits). -/
def cert_01000101000110101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101000110101010000001011010000110110 : ¬ HasNormalForm (cert_01000101000110101010000001011010000110110).T :=
  (cert_01000101000110101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101011000101010000001011010000110110` (41 bits). -/
def cert_01000101011000101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_01000101011000101010000001011010000110110 : ¬ HasNormalForm (cert_01000101011000101010000001011010000110110).T :=
  (cert_01000101011000101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010110100001100001101110` (41 bits). -/
def cert_00010001100011000010110100001100001101110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2)))))))
  W := (.lam (.app (.var 0) (.lam (.app (.var 0) (.mvar 0)))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2)))))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010110100001100001101110 : ¬ HasNormalForm (cert_00010001100011000010110100001100001101110).T :=
  (cert_00010001100011000010110100001100001101110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010110100001000111010110` (41 bits). -/
def cert_00010001100011000010110100001000111010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1)))))
  W := (.lam (.app (.lam (.app (.var 1) (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010110100001000111010110 : ¬ HasNormalForm (cert_00010001100011000010110100001000111010110).T :=
  (cert_00010001100011000010110100001000111010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010110100001010011010110` (41 bits). -/
def cert_00010001100011000010110100001010011010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010110100001010011010110 : ¬ HasNormalForm (cert_00010001100011000010110100001010011010110).T :=
  (cert_00010001100011000010110100001010011010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010110100001000110111010` (41 bits). -/
def cert_00010001100011000010110100001000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0)))))
  W := (.lam (.app (.lam (.app (.var 0) (.mvar 0))) (.var 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010110100001000110111010 : ¬ HasNormalForm (cert_00010001100011000010110100001000110111010).T :=
  (cert_00010001100011000010110100001000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010110100100000110111010` (41 bits). -/
def cert_00010001100011000010110100100000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.mvar 0)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010110100100000110111010 : ¬ HasNormalForm (cert_00010001100011000010110100100000110111010).T :=
  (cert_00010001100011000010110100100000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010001011011010000110110` (41 bits). -/
def cert_00010001100011000010001011011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 3
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010001011011010000110110 : ¬ HasNormalForm (cert_00010001100011000010001011011010000110110).T :=
  (cert_00010001100011000010001011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010100011011010000110110` (41 bits). -/
def cert_00010001100011000010100011011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010100011011010000110110 : ¬ HasNormalForm (cert_00010001100011000010100011011010000110110).T :=
  (cert_00010001100011000010100011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010100011101010000110110` (41 bits). -/
def cert_00010001100011000010100011101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010100011101010000110110 : ¬ HasNormalForm (cert_00010001100011000010100011101010000110110).T :=
  (cert_00010001100011000010100011101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010101001101010000110110` (41 bits). -/
def cert_00010001100011000010101001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010101001101010000110110 : ¬ HasNormalForm (cert_00010001100011000010101001101010000110110).T :=
  (cert_00010001100011000010101001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010001100001101110011010` (41 bits). -/
def cert_00010001100011000010001100001101110011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0)))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010001100001101110011010 : ¬ HasNormalForm (cert_00010001100011000010001100001101110011010).T :=
  (cert_00010001100011000010001100001101110011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010001011010000110111010` (41 bits). -/
def cert_00010001100011000010001011010000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010001011010000110111010 : ¬ HasNormalForm (cert_00010001100011000010001011010000110111010).T :=
  (cert_00010001100011000010001011010000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010001011011000011011010` (41 bits). -/
def cert_00010001100011000010001011011000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010001011011000011011010 : ¬ HasNormalForm (cert_00010001100011000010001011011000011011010).T :=
  (cert_00010001100011000010001011011000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100011000010001011101000011011010` (41 bits). -/
def cert_00010001100011000010001011101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100011000010001011101000011011010 : ¬ HasNormalForm (cert_00010001100011000010001011101000011011010).T :=
  (cert_00010001100011000010001011101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101001100010001100001011010000110110` (41 bits). -/
def cert_01000101001100010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.var 1)) (.lam (.var 0))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101001100010001100001011010000110110 : ¬ HasNormalForm (cert_01000101001100010001100001011010000110110).T :=
  (cert_01000101001100010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110100001011000000101101000011011010` (41 bits). -/
def cert_01000110100001011000000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.var 0))))
  kI := 4
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.var 0)))]

theorem kill_01000110100001011000000101101000011011010 : ¬ HasNormalForm (cert_01000110100001011000000101101000011011010).T :=
  (cert_01000110100001011000000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101001001101010000001011010000110110` (41 bits). -/
def cert_01000101001001101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101001001101010000001011010000110110 : ¬ HasNormalForm (cert_01000101001001101010000001011010000110110).T :=
  (cert_01000101001001101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101010010101010000001011010000110110` (41 bits). -/
def cert_01000101010010101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101010010101010000001011010000110110 : ¬ HasNormalForm (cert_01000101010010101010000001011010000110110).T :=
  (cert_01000101010010101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000011001000110001100001011010000110110` (41 bits). -/
def cert_01000011001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.var 1))) (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_01000011001000110001100001011010000110110 : ¬ HasNormalForm (cert_01000011001000110001100001011010000110110).T :=
  (cert_01000011001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001100000011110000110110000101101010` (41 bits). -/
def cert_00010001100000011110000110110000101101010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.lam (.app (.var 0) (.var 1)))))))) (.lam (.app (.app (.var 0) (.var 0)) (.var 0)))))
  kI := 3
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001100000011110000110110000101101010 : ¬ HasNormalForm (cert_00010001100000011110000110110000101101010).T :=
  (cert_00010001100000011110000110110000101101010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00000100010110111010000001011010000110110` (41 bits). -/
def cert_00000100010110111010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 2)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_00000100010110111010000001011010000110110 : ¬ HasNormalForm (cert_00000100010110111010000001011010000110110).T :=
  (cert_00000100010110111010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00000100010110001010000001011010000110110` (41 bits). -/
def cert_00000100010110001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_00000100010110001010000001011010000110110 : ¬ HasNormalForm (cert_00000100010110001010000001011010000110110).T :=
  (cert_00000100010110001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001000101101010000110110` (41 bits). -/
def cert_01000101101010000001000101101010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001000101101010000110110 : ¬ HasNormalForm (cert_01000101101010000001000101101010000110110).T :=
  (cert_01000101101010000001000101101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001010010011010000110110` (41 bits). -/
def cert_01000101101010000001010010011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001010010011010000110110 : ¬ HasNormalForm (cert_01000101101010000001010010011010000110110).T :=
  (cert_01000101101010000001010010011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001010001101010000110110` (41 bits). -/
def cert_01000101101010000001010001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001010001101010000110110 : ¬ HasNormalForm (cert_01000101101010000001010001101010000110110).T :=
  (cert_01000101101010000001010001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001010100101010000110110` (41 bits). -/
def cert_01000101101010000001010100101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001010100101010000110110 : ¬ HasNormalForm (cert_01000101101010000001010100101010000110110).T :=
  (cert_01000101101010000001010100101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101001001010000001011010000110110` (41 bits). -/
def cert_01000101101001001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.var 0)) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.var 0)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101001001010000001011010000110110 : ¬ HasNormalForm (cert_01000101101001001010000001011010000110110).T :=
  (cert_01000101101001001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110000100111000100001011010000110110` (41 bits). -/
def cert_01000110000100111000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 0))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 2)) (.lam (.var 0)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110000100111000100001011010000110110 : ¬ HasNormalForm (cert_01000110000100111000100001011010000110110).T :=
  (cert_01000110000100111000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110010000111000100001011010000110110` (41 bits). -/
def cert_01000110010000111000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.var 0)))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 2))) (.lam (.var 0))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110010000111000100001011010000110110 : ¬ HasNormalForm (cert_01000110010000111000100001011010000110110).T :=
  (cert_01000110010000111000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001001001011010000110110` (41 bits). -/
def cert_01000101101010000001001001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001001001011010000110110 : ¬ HasNormalForm (cert_01000101101010000001001001011010000110110).T :=
  (cert_01000101101010000001001001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110011010000110000001011010000110110` (41 bits). -/
def cert_01000110011010000110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.app (.var 0) (.var 0)))) (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 5
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110011010000110000001011010000110110 : ¬ HasNormalForm (cert_01000110011010000110000001011010000110110).T :=
  (cert_01000110011010000110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001011010000100100110110` (41 bits). -/
def cert_01000101101010000001011010000100100110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.lam (.var 0)) (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010000100100110110 : ¬ HasNormalForm (cert_01000101101010000001011010000100100110110).T :=
  (cert_01000101101010000001011010000100100110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001011010000101100010110` (41 bits). -/
def cert_01000101101010000001011010000101100010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1)))))
  W := (.lam (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010000101100010110 : ¬ HasNormalForm (cert_01000101101010000001011010000101100010110).T :=
  (cert_01000101101010000001011010000101100010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001011010000101001010110` (41 bits). -/
def cert_01000101101010000001011010000101001010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010000101001010110 : ¬ HasNormalForm (cert_01000101101010000001011010000101001010110).T :=
  (cert_01000101101010000001011010000101001010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001011010010010000110110` (41 bits). -/
def cert_01000101101010000001011010010010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.app (.lam (.var 0)) (.lam (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010010010000110110 : ¬ HasNormalForm (cert_01000101101010000001011010010010000110110).T :=
  (cert_01000101101010000001011010010010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000001011010010000011011010` (41 bits). -/
def cert_01000101101010000001011010010000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000001011010010000011011010 : ¬ HasNormalForm (cert_01000101101010000001011010010000011011010).T :=
  (cert_01000101101010000001011010010000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001011000111010000001011010000110110` (41 bits). -/
def cert_00010001011000111010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 2))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001011000111010000001011010000110110 : ¬ HasNormalForm (cert_00010001011000111010000001011010000110110).T :=
  (cert_00010001011000111010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001011000001010000001011010000110110` (41 bits). -/
def cert_00010001011000001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001011000001010000001011010000110110 : ¬ HasNormalForm (cert_00010001011000001010000001011010000110110).T :=
  (cert_00010001011000001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110100001100110000001011010000110110` (41 bits). -/
def cert_01000110100001100110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))))
  kI := 8
  binders := 0
  n0 := 0
  trail := [(.app (.app (.lam (.app (.var 0) (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.app (.lam (.app (.var 0) (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))]

theorem kill_01000110100001100110000001011010000110110 : ¬ HasNormalForm (cert_01000110100001100110000001011010000110110).T :=
  (cert_01000110100001100110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000110000001011010000110110000101101010` (41 bits). -/
def cert_01000110000001011010000110110000101101010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))) (.lam (.app (.app (.var 0) (.var 0)) (.var 0))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000110000001011010000110110000101101010 : ¬ HasNormalForm (cert_01000110000001011010000110110000101101010).T :=
  (cert_01000110000001011010000110110000101101010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00000101000110001100001011010000110110110` (41 bits). -/
def cert_00000101000110001100001011010000110110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 1))))
  kI := 1
  binders := 2
  n0 := 0
  trail := [(.var 1)]

theorem kill_00000101000110001100001011010000110110110 : ¬ HasNormalForm (cert_00000101000110001100001011010000110110110).T :=
  (cert_00000101000110001100001011010000110110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000110000001011010000110110` (41 bits). -/
def cert_01000101101010000110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kO := 1
  kD := 2
  kB := 3
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 4
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000110000001011010000110110 : ¬ HasNormalForm (cert_01000101101010000110000001011010000110110).T :=
  (cert_01000101101010000110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01010001011010100000010110100001101100010` (41 bits). -/
def cert_01010001011010100000010110100001101100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.var 0)))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_01010001011010100000010110100001101100010 : ¬ HasNormalForm (cert_01010001011010100000010110100001101100010).T :=
  (cert_01010001011010100000010110100001101100010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001011001101010000001011010000110110` (41 bits). -/
def cert_00010001011001101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.app (.var 0) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_00010001011001101010000001011010000110110 : ¬ HasNormalForm (cert_00010001011001101010000001011010000110110).T :=
  (cert_00010001011001101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000100000101101000011011010` (41 bits). -/
def cert_01000101101010000100000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0)))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000100000101101000011011010 : ¬ HasNormalForm (cert_01000101101010000100000101101000011011010).T :=
  (cert_01000101101010000100000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010001010110101010000001011010000110110` (41 bits). -/
def cert_00010001010110101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.app (.var 0) (.var 0)) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_00010001010110101010000001011010000110110 : ¬ HasNormalForm (cert_00010001010110101010000001011010000110110).T :=
  (cert_00010001010110101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010000100100001011010000110110` (41 bits). -/
def cert_01000101101010000100100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010000100100001011010000110110 : ¬ HasNormalForm (cert_01000101101010000100100001011010000110110).T :=
  (cert_01000101101010000100100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00010100010110101000000101101000011011010` (41 bits). -/
def cert_00010100010110101000000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.var 0)))
  kI := 2
  binders := 1
  n0 := 0
  trail := [(.var 0)]

theorem kill_00010100010110101000000101101000011011010 : ¬ HasNormalForm (cert_00010100010110101000000101101000011011010).T :=
  (cert_00010100010110101000000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `00000100010110001101100001011010000110110` (41 bits). -/
def cert_00000100010110001101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 1))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := [(.var 0)]

theorem kill_00000100010110001101100001011010000110110 : ¬ HasNormalForm (cert_00000100010110001101100001011010000110110).T :=
  (cert_00000100010110001101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101101010010010000001011010000110110` (41 bits). -/
def cert_01000101101010010010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.var 0)) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.app (.lam (.var 0)) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_01000101101010010010000001011010000110110 : ¬ HasNormalForm (cert_01000101101010010010000001011010000110110).T :=
  (cert_01000101101010010010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `01000101011010100010000001011010000110110` (41 bits). -/
def cert_01000101011010100010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.var 0) (.var 0)) (.var 0)) (.lam (.var 0)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_01000101011010100010000001011010000110110 : ¬ HasNormalForm (cert_01000101011010100010000001011010000110110).T :=
  (cert_01000101011010100010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

end Blc.Certs
