/-
Generated by certlean — DO NOT EDIT. 30 RATCHET kill(s) at n=39.
Every obligation is replayed by the Lean kernel (`by decide`).
-/
import Blc.Ratchet

namespace Blc.Certs

/-- `000001000101101010000001011010000110110` (39 bits). -/
def cert_000001000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_000001000101101010000001011010000110110 : ¬ HasNormalForm (cert_000001000101101010000001011010000110110).T :=
  (cert_000001000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `000100010110001010000001011010000110110` (39 bits). -/
def cert_000100010110001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_000100010110001010000001011010000110110 : ¬ HasNormalForm (cert_000100010110001010000001011010000110110).T :=
  (cert_000100010110001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `000100010110001101100001011010000110110` (39 bits). -/
def cert_000100010110001101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 1))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.var 0)]

theorem kill_000100010110001101100001011010000110110 : ¬ HasNormalForm (cert_000100010110001101100001011010000110110).T :=
  (cert_000100010110001101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010000010111010110000001011010000110110` (39 bits). -/
def cert_010000010111010110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.var 0)) (.var 1)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_010000010111010110000001011010000110110 : ¬ HasNormalForm (cert_010000010111010110000001011010000110110).T :=
  (cert_010000010111010110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001000110001110100001011010000110110` (39 bits). -/
def cert_010001000110001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 2)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000110001110100001011010000110110 : ¬ HasNormalForm (cert_010001000110001110100001011010000110110).T :=
  (cert_010001000110001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001000111000110100001011010000110110` (39 bits). -/
def cert_010001000111000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 1) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000111000110100001011010000110110 : ¬ HasNormalForm (cert_010001000111000110100001011010000110110).T :=
  (cert_010001000111000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001000111010001100001011010000110110` (39 bits). -/
def cert_010001000111010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 1) (.var 0))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001000111010001100001011010000110110 : ¬ HasNormalForm (cert_010001000111010001100001011010000110110).T :=
  (cert_010001000111010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001010011010001100001011010000110110` (39 bits). -/
def cert_010001010011010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001010011010001100001011010000110110 : ¬ HasNormalForm (cert_010001010011010001100001011010000110110).T :=
  (cert_010001010011010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001010110101010000001011010000110110` (39 bits). -/
def cert_010001010110101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.var 0) (.var 0)) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_010001010110101010000001011010000110110 : ¬ HasNormalForm (cert_010001010110101010000001011010000110110).T :=
  (cert_010001010110101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001011000001010000001011010000110110` (39 bits). -/
def cert_010001011000001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001011000001010000001011010000110110 : ¬ HasNormalForm (cert_010001011000001010000001011010000110110).T :=
  (cert_010001011000001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001011000110001100001011010000110110` (39 bits). -/
def cert_010001011000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_010001011000110001100001011010000110110 : ¬ HasNormalForm (cert_010001011000110001100001011010000110110).T :=
  (cert_010001011000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001011001101010000001011010000110110` (39 bits). -/
def cert_010001011001101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.app (.var 0) (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001011001101010000001011010000110110 : ¬ HasNormalForm (cert_010001011001101010000001011010000110110).T :=
  (cert_010001011001101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100000011110000110110000101101010` (39 bits). -/
def cert_010001100000011110000110110000101101010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.lam (.app (.var 0) (.var 1)))))))) (.lam (.app (.app (.var 0) (.var 0)) (.var 0))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100000011110000110110000101101010 : ¬ HasNormalForm (cert_010001100000011110000110110000101101010).T :=
  (cert_010001100000011110000110110000101101010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100000011110100001011010000110110` (39 bits). -/
def cert_010001100000011110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))))
  kO := 2
  kD := 2
  kB := 3
  T := (.app (.lam (.app (.var 0) (.lam (.lam (.app (.var 2) (.var 0)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100000011110100001011010000110110 : ¬ HasNormalForm (cert_010001100000011110100001011010000110110).T :=
  (cert_010001100000011110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100001001110100001011010000110110` (39 bits). -/
def cert_010001100001001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0)))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 2)) (.var 0))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100001001110100001011010000110110 : ¬ HasNormalForm (cert_010001100001001110100001011010000110110).T :=
  (cert_010001100001001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100001100011100001011010000110110` (39 bits). -/
def cert_010001100001100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.var 0) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kO := 1
  kD := 2
  kB := 3
  T := (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.lam (.var 2)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100001100011100001011010000110110 : ¬ HasNormalForm (cert_010001100001100011100001011010000110110).T :=
  (cert_010001100001100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010001011010000110111010` (39 bits). -/
def cert_010001100011000010001011010000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011010000110111010 : ¬ HasNormalForm (cert_010001100011000010001011010000110111010).T :=
  (cert_010001100011000010001011010000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010001011011000011011010` (39 bits). -/
def cert_010001100011000010001011011000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011011000011011010 : ¬ HasNormalForm (cert_010001100011000010001011011000011011010).T :=
  (cert_010001100011000010001011011000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010001011011010000110110` (39 bits). -/
def cert_010001100011000010001011011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 3
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011011010000110110 : ¬ HasNormalForm (cert_010001100011000010001011011010000110110).T :=
  (cert_010001100011000010001011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010001011101000011011010` (39 bits). -/
def cert_010001100011000010001011101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001011101000011011010 : ¬ HasNormalForm (cert_010001100011000010001011101000011011010).T :=
  (cert_010001100011000010001011101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010001100001101110011010` (39 bits). -/
def cert_010001100011000010001100001101110011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0)))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))) (.app (.var 0) (.var 0)))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010001100001101110011010 : ¬ HasNormalForm (cert_010001100011000010001100001101110011010).T :=
  (cert_010001100011000010001100001101110011010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010100011011010000110110` (39 bits). -/
def cert_010001100011000010100011011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 0) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010100011011010000110110 : ¬ HasNormalForm (cert_010001100011000010100011011010000110110).T :=
  (cert_010001100011000010100011011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010100011101010000110110` (39 bits). -/
def cert_010001100011000010100011101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 1) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010100011101010000110110 : ¬ HasNormalForm (cert_010001100011000010100011101010000110110).T :=
  (cert_010001100011000010100011101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010101001101010000110110` (39 bits). -/
def cert_010001100011000010101001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 1)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010101001101010000110110 : ¬ HasNormalForm (cert_010001100011000010101001101010000110110).T :=
  (cert_010001100011000010101001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010110100001000110111010` (39 bits). -/
def cert_010001100011000010110100001000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0)))))
  W := (.lam (.app (.lam (.app (.var 0) (.mvar 0))) (.var 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 0) (.var 2))) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001000110111010 : ¬ HasNormalForm (cert_010001100011000010110100001000110111010).T :=
  (cert_010001100011000010110100001000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010110100001000111010110` (39 bits). -/
def cert_010001100011000010110100001000111010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1)))))
  W := (.lam (.app (.lam (.app (.var 1) (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 0))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001000111010110 : ¬ HasNormalForm (cert_010001100011000010110100001000111010110).T :=
  (cert_010001100011000010110100001000111010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010110100001010011010110` (39 bits). -/
def cert_010001100011000010110100001010011010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 0)) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001010011010110 : ¬ HasNormalForm (cert_010001100011000010110100001010011010110).T :=
  (cert_010001100011000010110100001010011010110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010110100001100001101110` (39 bits). -/
def cert_010001100011000010110100001100001101110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2)))))))
  W := (.lam (.app (.var 0) (.lam (.app (.var 0) (.mvar 0)))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.lam (.app (.var 0) (.var 2))))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100001100001101110 : ¬ HasNormalForm (cert_010001100011000010110100001100001101110).T :=
  (cert_010001100011000010110100001100001101110).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100011000010110100100000110111010` (39 bits). -/
def cert_010001100011000010110100100000110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.mvar 0)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 2)))) (.var 0)))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100011000010110100100000110111010 : ¬ HasNormalForm (cert_010001100011000010110100100000110111010).T :=
  (cert_010001100011000010110100100000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

/-- `010001100100001110100001011010000110110` (39 bits). -/
def cert_010001100100001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 2))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_010001100100001110100001011010000110110 : ¬ HasNormalForm (cert_010001100100001110100001011010000110110).T :=
  (cert_010001100100001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

end Blc.Certs
