/-
Generated by certlean — DO NOT EDIT. 4 RATCHET kill(s) at n=37.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.HeadTower
import Blc.Selector
import Blc.Wire

namespace Blc.Certs

/-- `0001000101101010000001011010000110110` (37 bits, RATCHET). -/
def cert_0001000101101010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000101101010000001011010000110110 : ¬ HasNormalForm (cert_0001000101101010000001011010000110110).T :=
  (cert_0001000101101010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000101101010000001011010000110110 :
    blcCode (cert_0001000101101010000001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110100001100001010110001011010` (37 bits, RATCHET2). -/
def cert_0001000110100001100001010110001011010 : HTRCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  W := (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))
  E := (.lam (.var 0))
  kB := 0
  kO := 1
  kS := 1
  kP := 3
  kBounce := 3
  kE := 7
  T := (.lam (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.app (.var 0) (.lam (.var 0))) (.var 1)) (.var 0)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110100001100001010110001011010 : ¬ HasNormalForm (cert_0001000110100001100001010110001011010).T :=
  (cert_0001000110100001100001010110001011010).noNormalForm (HTRCert.valid_of_check (by decide))

theorem wire_0001000110100001100001010110001011010 :
    blcCode (cert_0001000110100001100001010110001011010).T = [false, false, false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, false, true, true, false, false, false, true, false, true, true, false, true, false] := by decide

/-- `0100010110001010000001011010000110110` (37 bits, RATCHET). -/
def cert_0100010110001010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100010110001010000001011010000110110 : ¬ HasNormalForm (cert_0100010110001010000001011010000110110).T :=
  (cert_0100010110001010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010110001010000001011010000110110 :
    blcCode (cert_0100010110001010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110100001100001011000001111010` (37 bits, SELECTOR). -/
def cert_0001000110100001100001011000001111010 : SelCert where
  A := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.mvar 0)))) (.var 0)))
  C0 := (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))
  P := (.lam (.lam (.mvar 0)))
  kO := 1
  kF := 1
  kSel := 3
  kB := 0
  T := (.lam (.app (.lam (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.lam (.lam (.var 3)))) (.var 0)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110100001100001011000001111010 : ¬ HasNormalForm (cert_0001000110100001100001011000001111010).T :=
  (cert_0001000110100001100001011000001111010).noNormalForm (SelCert.valid_of_check (by decide))

theorem wire_0001000110100001100001011000001111010 :
    blcCode (cert_0001000110100001100001011000001111010).T = [false, false, false, true, false, false, false, true, true, false, true, false, false, false, false, true, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, true, true, true, false, true, false] := by decide

end Blc.Certs
