/-
Generated by certlean — DO NOT EDIT. 58 RATCHET kill(s) at n=40.
Every obligation is replayed by the Lean kernel (`by decide`),
and each `wire_*` theorem pins the certified term to its named bits.
-/
import Blc.Ratchet
import Blc.Wire

namespace Blc.Certs

/-- `0000000001000110001100001011010000110110` (40 bits). -/
def cert_0000000001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.lam (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))))
  kI := 1
  binders := 4
  n0 := 0
  trail := []

theorem kill_0000000001000110001100001011010000110110 : ¬ HasNormalForm (cert_0000000001000110001100001011010000110110).T :=
  (cert_0000000001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000000001000110001100001011010000110110 :
    blcCode (cert_0000000001000110001100001011010000110110).T = [false, false, false, false, false, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0000010000011100011100001011010000110110` (40 bits). -/
def cert_0000010000011100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.lam (.app (.var 1) (.lam (.var 2))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 3
  n0 := 0
  trail := []

theorem kill_0000010000011100011100001011010000110110 : ¬ HasNormalForm (cert_0000010000011100011100001011010000110110).T :=
  (cert_0000010000011100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000010000011100011100001011010000110110 :
    blcCode (cert_0000010000011100011100001011010000110110).T = [false, false, false, false, false, true, false, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0000010001011000110100001011010000110110` (40 bits). -/
def cert_0000010001011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_0000010001011000110100001011010000110110 : ¬ HasNormalForm (cert_0000010001011000110100001011010000110110).T :=
  (cert_0000010001011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000010001011000110100001011010000110110 :
    blcCode (cert_0000010001011000110100001011010000110110).T = [false, false, false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0000010001011011010000001011010000110110` (40 bits). -/
def cert_0000010001011011010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := []

theorem kill_0000010001011011010000001011010000110110 : ¬ HasNormalForm (cert_0000010001011011010000001011010000110110).T :=
  (cert_0000010001011011010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000010001011011010000001011010000110110 :
    blcCode (cert_0000010001011011010000001011010000110110).T = [false, false, false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0000010001100110001100001011010000110110` (40 bits). -/
def cert_0000010001100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.lam (.app (.var 0) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 2
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))))]

theorem kill_0000010001100110001100001011010000110110 : ¬ HasNormalForm (cert_0000010001100110001100001011010000110110).T :=
  (cert_0000010001100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000010001100110001100001011010000110110 :
    blcCode (cert_0000010001100110001100001011010000110110).T = [false, false, false, false, false, true, false, false, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0000010100011000110000101101000011011010` (40 bits). -/
def cert_0000010100011000110000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.var 0))))
  kI := 1
  binders := 2
  n0 := 0
  trail := [(.var 0)]

theorem kill_0000010100011000110000101101000011011010 : ¬ HasNormalForm (cert_0000010100011000110000101101000011011010).T :=
  (cert_0000010100011000110000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0000010100011000110000101101000011011010 :
    blcCode (cert_0000010100011000110000101101000011011010).T = [false, false, false, false, false, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `0001000100011000110000101101000011011010` (40 bits). -/
def cert_0001000100011000110000101101000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.var 0)))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000100011000110000101101000011011010 : ¬ HasNormalForm (cert_0001000100011000110000101101000011011010).T :=
  (cert_0001000100011000110000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000100011000110000101101000011011010 :
    blcCode (cert_0001000100011000110000101101000011011010).T = [false, false, false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `0001000100011000110100001011010000110110` (40 bits). -/
def cert_0001000100011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000100011000110100001011010000110110 : ¬ HasNormalForm (cert_0001000100011000110100001011010000110110).T :=
  (cert_0001000100011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000100011000110100001011010000110110 :
    blcCode (cert_0001000100011000110100001011010000110110).T = [false, false, false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000100100110001100001011010000110110` (40 bits). -/
def cert_0001000100100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.lam (.var 0)) (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000100100110001100001011010000110110 : ¬ HasNormalForm (cert_0001000100100110001100001011010000110110).T :=
  (cert_0001000100100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000100100110001100001011010000110110 :
    blcCode (cert_0001000100100110001100001011010000110110).T = [false, false, false, true, false, false, false, true, false, false, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000101001010001100001011010000110110` (40 bits). -/
def cert_0001000101001010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000101001010001100001011010000110110 : ¬ HasNormalForm (cert_0001000101001010001100001011010000110110).T :=
  (cert_0001000101001010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000101001010001100001011010000110110 :
    blcCode (cert_0001000101001010001100001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, false, false, true, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000101100011000100001011010000110110` (40 bits). -/
def cert_0001000101100011000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_0001000101100011000100001011010000110110 : ¬ HasNormalForm (cert_0001000101100011000100001011010000110110).T :=
  (cert_0001000101100011000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000101100011000100001011010000110110 :
    blcCode (cert_0001000101100011000100001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000101100011010000001011010000110110` (40 bits). -/
def cert_0001000101100011010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000101100011010000001011010000110110 : ¬ HasNormalForm (cert_0001000101100011010000001011010000110110).T :=
  (cert_0001000101100011010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000101100011010000001011010000110110 :
    blcCode (cert_0001000101100011010000001011010000110110).T = [false, false, false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110000100101100001011010000110110` (40 bits). -/
def cert_0001000110000100101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 0)) (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110000100101100001011010000110110 : ¬ HasNormalForm (cert_0001000110000100101100001011010000110110).T :=
  (cert_0001000110000100101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110000100101100001011010000110110 :
    blcCode (cert_0001000110000100101100001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, false, true, false, false, true, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110000101101000011011000011000110` (40 bits). -/
def cert_0001000110000101101000011011000011000110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.var 0) (.lam (.var 1))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110000101101000011011000011000110 : ¬ HasNormalForm (cert_0001000110000101101000011011000011000110).T :=
  (cert_0001000110000101101000011011000011000110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110000101101000011011000011000110 :
    blcCode (cert_0001000110000101101000011011000011000110).T = [false, false, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, false, true, true, false, false, false, true, true, false] := by decide

/-- `0001000110001100001000101101000011011010` (40 bits). -/
def cert_0001000110001100001000101101000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001000101101000011011010 : ¬ HasNormalForm (cert_0001000110001100001000101101000011011010).T :=
  (cert_0001000110001100001000101101000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001000101101000011011010 :
    blcCode (cert_0001000110001100001000101101000011011010).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `0001000110001100001000101101010000110110` (40 bits). -/
def cert_0001000110001100001000101101010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 4
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001000101101010000110110 : ¬ HasNormalForm (cert_0001000110001100001000101101010000110110).T :=
  (cert_0001000110001100001000101101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001000101101010000110110 :
    blcCode (cert_0001000110001100001000101101010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001001001011010000110110` (40 bits). -/
def cert_0001000110001100001001001011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.var 0)) (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001001001011010000110110 : ¬ HasNormalForm (cert_0001000110001100001001001011010000110110).T :=
  (cert_0001000110001100001001001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001001001011010000110110 :
    blcCode (cert_0001000110001100001001001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, true, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001010001101010000110110` (40 bits). -/
def cert_0001000110001100001010001101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 0) (.var 0))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001010001101010000110110 : ¬ HasNormalForm (cert_0001000110001100001010001101010000110110).T :=
  (cert_0001000110001100001010001101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001010001101010000110110 :
    blcCode (cert_0001000110001100001010001101010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001010010011010000110110` (40 bits). -/
def cert_0001000110001100001010010011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.var 0)) (.app (.var 0) (.var 0))) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001010010011010000110110 : ¬ HasNormalForm (cert_0001000110001100001010010011010000110110).T :=
  (cert_0001000110001100001010010011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001010010011010000110110 :
    blcCode (cert_0001000110001100001010010011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, true, false, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001010100101010000110110` (40 bits). -/
def cert_0001000110001100001010100101010000110110 : RatchetCert where
  A := (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.app (.lam (.var 0)) (.var 0)) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001010100101010000110110 : ¬ HasNormalForm (cert_0001000110001100001010100101010000110110).T :=
  (cert_0001000110001100001010100101010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001010100101010000110110 :
    blcCode (cert_0001000110001100001010100101010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, true, false, false, true, false, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001011010000100100110110` (40 bits). -/
def cert_0001000110001100001011010000100100110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1))))))
  W := (.lam (.app (.lam (.var 0)) (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.var 0)) (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010000100100110110 : ¬ HasNormalForm (cert_0001000110001100001011010000100100110110).T :=
  (cert_0001000110001100001011010000100100110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001011010000100100110110 :
    blcCode (cert_0001000110001100001011010000100100110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, false, true, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100001011010000101001010110` (40 bits). -/
def cert_0001000110001100001011010000101001010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 0)) (.var 0)) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010000101001010110 : ¬ HasNormalForm (cert_0001000110001100001011010000101001010110).T :=
  (cert_0001000110001100001011010000101001010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001011010000101001010110 :
    blcCode (cert_0001000110001100001011010000101001010110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, false, false, true, false, true, false, true, true, false] := by decide

/-- `0001000110001100001011010000101100010110` (40 bits). -/
def cert_0001000110001100001011010000101100010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1)))))
  W := (.lam (.app (.app (.var 0) (.lam (.var 0))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.var 0))) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010000101100010110 : ¬ HasNormalForm (cert_0001000110001100001011010000101100010110).T :=
  (cert_0001000110001100001011010000101100010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001011010000101100010110 :
    blcCode (cert_0001000110001100001011010000101100010110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, true, false, false, false, true, false, true, true, false] := by decide

/-- `0001000110001100001011010010000011011010` (40 bits). -/
def cert_0001000110001100001011010010000011011010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0))))
  W := (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.mvar 0))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0)))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.lam (.app (.var 0) (.var 1)))) (.var 0))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010010000011011010 : ¬ HasNormalForm (cert_0001000110001100001011010010000011011010).T :=
  (cert_0001000110001100001011010010000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001011010010000011011010 :
    blcCode (cert_0001000110001100001011010010000011011010).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, true, false, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `0001000110001100001011010010010000110110` (40 bits). -/
def cert_0001000110001100001011010010010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  W := (.app (.lam (.var 0)) (.lam (.app (.var 0) (.mvar 0))))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.app (.lam (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100001011010010010000110110 : ¬ HasNormalForm (cert_0001000110001100001011010010010000110110).T :=
  (cert_0001000110001100001011010010010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100001011010010010000110110 :
    blcCode (cert_0001000110001100001011010010010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, true, false, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110001100100100001011010000110110` (40 bits). -/
def cert_0001000110001100100100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.app (.lam (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110001100100100001011010000110110 : ¬ HasNormalForm (cert_0001000110001100100100001011010000110110).T :=
  (cert_0001000110001100100100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110001100100100001011010000110110 :
    blcCode (cert_0001000110001100100100001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, true, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110010000110100001011010000110110` (40 bits). -/
def cert_0001000110010000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.lam (.var 1))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.app (.lam (.lam (.var 1))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110010000110100001011010000110110 : ¬ HasNormalForm (cert_0001000110010000110100001011010000110110).T :=
  (cert_0001000110010000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110010000110100001011010000110110 :
    blcCode (cert_0001000110010000110100001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, true, false, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001000110010010001100001011010000110110` (40 bits). -/
def cert_0001000110010010001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.app (.lam (.var 0)) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.lam (.app (.lam (.app (.var 0) (.app (.lam (.var 0)) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001000110010010001100001011010000110110 : ¬ HasNormalForm (cert_0001000110010010001100001011010000110110).T :=
  (cert_0001000110010010001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001000110010010001100001011010000110110 :
    blcCode (cert_0001000110010010001100001011010000110110).T = [false, false, false, true, false, false, false, true, true, false, false, true, false, false, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001001001000110001100001011010000110110` (40 bits). -/
def cert_0001001001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.lam (.var 0)) (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001001001000110001100001011010000110110 : ¬ HasNormalForm (cert_0001001001000110001100001011010000110110).T :=
  (cert_0001001001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001001001000110001100001011010000110110 :
    blcCode (cert_0001001001000110001100001011010000110110).T = [false, false, false, true, false, false, true, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001010000011000110100001011010000110110` (40 bits). -/
def cert_0001010000011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.lam (.app (.var 0) (.lam (.var 1))))) (.var 0)) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001010000011000110100001011010000110110 : ¬ HasNormalForm (cert_0001010000011000110100001011010000110110).T :=
  (cert_0001010000011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001010000011000110100001011010000110110 :
    blcCode (cert_0001010000011000110100001011010000110110).T = [false, false, false, true, false, true, false, false, false, false, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0001010001100011000010110100001101100010` (40 bits). -/
def cert_0001010001100011000010110100001101100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 0))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.lam (.var 0))]

theorem kill_0001010001100011000010110100001101100010 : ¬ HasNormalForm (cert_0001010001100011000010110100001101100010).T :=
  (cert_0001010001100011000010110100001101100010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001010001100011000010110100001101100010 :
    blcCode (cert_0001010001100011000010110100001101100010).T = [false, false, false, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, true, false] := by decide

/-- `0001010010000110001100001011010000110110` (40 bits). -/
def cert_0001010010000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.lam (.app (.app (.lam (.var 0)) (.lam (.app (.var 0) (.lam (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0001010010000110001100001011010000110110 : ¬ HasNormalForm (cert_0001010010000110001100001011010000110110).T :=
  (cert_0001010010000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0001010010000110001100001011010000110110 :
    blcCode (cert_0001010010000110001100001011010000110110).T = [false, false, false, true, false, true, false, false, true, false, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100000001111000111100001011010000110110` (40 bits). -/
def cert_0100000001111000111100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.lam (.app (.var 2) (.lam (.var 3)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 2
  n0 := 0
  trail := []

theorem kill_0100000001111000111100001011010000110110 : ¬ HasNormalForm (cert_0100000001111000111100001011010000110110).T :=
  (cert_0100000001111000111100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100000001111000111100001011010000110110 :
    blcCode (cert_0100000001111000111100001011010000110110).T = [false, true, false, false, false, false, false, false, false, true, true, true, true, false, false, false, true, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100000101110001110100001011010000110110` (40 bits). -/
def cert_0100000101110001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.lam (.var 2))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 1
  n0 := 0
  trail := [(.var 0)]

theorem kill_0100000101110001110100001011010000110110 : ¬ HasNormalForm (cert_0100000101110001110100001011010000110110).T :=
  (cert_0100000101110001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100000101110001110100001011010000110110 :
    blcCode (cert_0100000101110001110100001011010000110110).T = [false, true, false, false, false, false, false, true, false, true, true, true, false, false, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100000101110110110000001011010000110110` (40 bits). -/
def cert_0100000101110110110000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.lam (.app (.app (.var 1) (.var 1)) (.var 1)))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0100000101110110110000001011010000110110 : ¬ HasNormalForm (cert_0100000101110110110000001011010000110110).T :=
  (cert_0100000101110110110000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100000101110110110000001011010000110110 :
    blcCode (cert_0100000101110110110000001011010000110110).T = [false, true, false, false, false, false, false, true, false, true, true, true, false, true, true, false, true, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010001100011000010110100001101100010` (40 bits). -/
def cert_0100010001100011000010110100001101100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.var 0)))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100010001100011000010110100001101100010 : ¬ HasNormalForm (cert_0100010001100011000010110100001101100010).T :=
  (cert_0100010001100011000010110100001101100010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010001100011000010110100001101100010 :
    blcCode (cert_0100010001100011000010110100001101100010).T = [false, true, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, true, false] := by decide

/-- `0100010001110001110100001011010000110110` (40 bits). -/
def cert_0100010001110001110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.lam (.app (.var 1) (.lam (.var 2)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100010001110001110100001011010000110110 : ¬ HasNormalForm (cert_0100010001110001110100001011010000110110).T :=
  (cert_0100010001110001110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010001110001110100001011010000110110 :
    blcCode (cert_0100010001110001110100001011010000110110).T = [false, true, false, false, false, true, false, false, false, true, true, true, false, false, false, true, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010101100011010100001011010000110110` (40 bits). -/
def cert_0100010101100011010100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.app (.var 0) (.lam (.var 1))) (.var 0)) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))), (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_0100010101100011010100001011010000110110 : ¬ HasNormalForm (cert_0100010101100011010100001011010000110110).T :=
  (cert_0100010101100011010100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010101100011010100001011010000110110 :
    blcCode (cert_0100010101100011010100001011010000110110).T = [false, true, false, false, false, true, false, true, false, true, true, false, false, false, true, true, false, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010110000011010000001011010000110110` (40 bits). -/
def cert_0100010110000011010000001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.lam (.var 1)))) (.var 0))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100010110000011010000001011010000110110 : ¬ HasNormalForm (cert_0100010110000011010000001011010000110110).T :=
  (cert_0100010110000011010000001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010110000011010000001011010000110110 :
    blcCode (cert_0100010110000011010000001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, false, false, true, true, false, true, false, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010110001100000100001011010000110110` (40 bits). -/
def cert_0100010110001100000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.lam (.lam (.var 0))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.var 0)))]

theorem kill_0100010110001100000100001011010000110110 : ¬ HasNormalForm (cert_0100010110001100000100001011010000110110).T :=
  (cert_0100010110001100000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010110001100000100001011010000110110 :
    blcCode (cert_0100010110001100000100001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, false, false, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010110001100110100001011010000110110` (40 bits). -/
def cert_0100010110001100110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.lam (.var 1))) (.app (.var 0) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))]

theorem kill_0100010110001100110100001011010000110110 : ¬ HasNormalForm (cert_0100010110001100110100001011010000110110).T :=
  (cert_0100010110001100110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010110001100110100001011010000110110 :
    blcCode (cert_0100010110001100110100001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, false, true, true, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100010110011000110100001011010000110110` (40 bits). -/
def cert_0100010110011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.app (.var 0) (.app (.var 0) (.lam (.var 1)))) (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))), (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))]

theorem kill_0100010110011000110100001011010000110110 : ¬ HasNormalForm (cert_0100010110011000110100001011010000110110).T :=
  (cert_0100010110011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100010110011000110100001011010000110110 :
    blcCode (cert_0100010110011000110100001011010000110110).T = [false, true, false, false, false, true, false, true, true, false, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011000010011101100001011010000110110` (40 bits). -/
def cert_0100011000010011101100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.app (.lam (.var 2)) (.var 1))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000010011101100001011010000110110 : ¬ HasNormalForm (cert_0100011000010011101100001011010000110110).T :=
  (cert_0100011000010011101100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000010011101100001011010000110110 :
    blcCode (cert_0100011000010011101100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, true, false, false, true, true, true, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011000011100011100001011010000110110` (40 bits). -/
def cert_0100011000011100011100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.app (.var 1) (.lam (.var 2)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.var 0) (.lam (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))))]

theorem kill_0100011000011100011100001011010000110110 : ¬ HasNormalForm (cert_0100011000011100011100001011010000110110).T :=
  (cert_0100011000011100011100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000011100011100001011010000110110 :
    blcCode (cert_0100011000011100011100001011010000110110).T = [false, true, false, false, false, true, true, false, false, false, false, true, true, true, false, false, false, true, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011000110000100010110110000110111010` (40 bits). -/
def cert_0100011000110000100010110110000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 0) (.var 1)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000100010110110000110111010 : ¬ HasNormalForm (cert_0100011000110000100010110110000110111010).T :=
  (cert_0100011000110000100010110110000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000100010110110000110111010 :
    blcCode (cert_0100011000110000100010110110000110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, false, true, true, false, false, false, false, true, true, false, true, true, true, false, true, false] := by decide

/-- `0100011000110000100010111010000110111010` (40 bits). -/
def cert_0100011000110000100010111010000110111010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 0)) (.lam (.app (.var 0) (.var 2))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000100010111010000110111010 : ¬ HasNormalForm (cert_0100011000110000100010111010000110111010).T :=
  (cert_0100011000110000100010111010000110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000100010111010000110111010 :
    blcCode (cert_0100011000110000100010111010000110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, true, false, false, false, false, true, true, false, true, true, true, false, true, false] := by decide

/-- `0100011000110000100010111011000011011010` (40 bits). -/
def cert_0100011000110000100010111011000011011010 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0)))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.lam (.app (.var 0) (.var 1))))) (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000100010111011000011011010 : ¬ HasNormalForm (cert_0100011000110000100010111011000011011010).T :=
  (cert_0100011000110000100010111011000011011010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000100010111011000011011010 :
    blcCode (cert_0100011000110000100010111011000011011010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, true, true, false, false, false, false, true, true, false, true, true, false, true, false] := by decide

/-- `0100011000110000100010111011010000110110` (40 bits). -/
def cert_0100011000110000100010111011010000110110 : RatchetCert where
  A := (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.lam (.app (.app (.var 1) (.var 1)) (.var 0))) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000100010111011010000110110 : ¬ HasNormalForm (cert_0100011000110000100010111011010000110110).T :=
  (cert_0100011000110000100010111011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000100010111011010000110110 :
    blcCode (cert_0100011000110000100010111011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, false, false, true, false, true, true, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011000110000101000111011010000110110` (40 bits). -/
def cert_0100011000110000101000111011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.lam (.app (.var 1) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.lam (.app (.var 1) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 2
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.lam (.app (.var 1) (.var 1))) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000101000111011010000110110 : ¬ HasNormalForm (cert_0100011000110000101000111011010000110110).T :=
  (cert_0100011000110000101000111011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000101000111011010000110110 :
    blcCode (cert_0100011000110000101000111011010000110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, false, false, false, true, true, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011000110000101101000010001110111010` (40 bits). -/
def cert_0100011000110000101101000010001110111010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 0)))))
  W := (.lam (.app (.lam (.app (.var 1) (.mvar 0))) (.var 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 0))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.lam (.app (.var 1) (.var 2))) (.var 0))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000101101000010001110111010 : ¬ HasNormalForm (cert_0100011000110000101101000010001110111010).T :=
  (cert_0100011000110000101101000010001110111010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000101101000010001110111010 :
    blcCode (cert_0100011000110000101101000010001110111010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, false, false, true, true, true, false, true, true, true, false, true, false] := by decide

/-- `0100011000110000101101000010100110110110` (40 bits). -/
def cert_0100011000110000101101000010100110110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 1)) (.var 1)))))
  W := (.lam (.app (.app (.lam (.var 1)) (.mvar 0)) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 1)) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.lam (.var 1)) (.var 1)) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000101101000010100110110110 : ¬ HasNormalForm (cert_0100011000110000101101000010100110110110).T :=
  (cert_0100011000110000101101000010100110110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000101101000010100110110110 :
    blcCode (cert_0100011000110000101101000010100110110110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, false, false, true, true, false, true, true, false, true, true, false] := by decide

/-- `0100011000110000101101000010110000010110` (40 bits). -/
def cert_0100011000110000101101000010110000010110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 1)))))
  W := (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 1))))))
  kO := 1
  kD := 4
  kB := 1
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.app (.var 0) (.lam (.lam (.var 0)))) (.var 1))))))
  kI := 1
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110000101101000010110000010110 : ¬ HasNormalForm (cert_0100011000110000101101000010110000010110).T :=
  (cert_0100011000110000101101000010110000010110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110000101101000010110000010110 :
    blcCode (cert_0100011000110000101101000010110000010110).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, false, true, true, false, false, false, false, false, true, false, true, true, false] := by decide

/-- `0100011000110010000010110100001101100010` (40 bits). -/
def cert_0100011000110010000010110100001101100010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 0))))
  kO := 1
  kD := 2
  kB := 2
  T := (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.app (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.var 0))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0100011000110010000010110100001101100010 : ¬ HasNormalForm (cert_0100011000110010000010110100001101100010).T :=
  (cert_0100011000110010000010110100001101100010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011000110010000010110100001101100010 :
    blcCode (cert_0100011000110010000010110100001101100010).T = [false, true, false, false, false, true, true, false, false, false, true, true, false, false, true, false, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, true, false] := by decide

/-- `0100011001011000110100001011010000110110` (40 bits). -/
def cert_0100011001011000110100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.app (.app (.var 0) (.lam (.var 1))) (.var 0)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := [(.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))), (.app (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))), (.lam (.app (.var 0) (.app (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))]

theorem kill_0100011001011000110100001011010000110110 : ¬ HasNormalForm (cert_0100011001011000110100001011010000110110).T :=
  (cert_0100011001011000110100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011001011000110100001011010000110110 :
    blcCode (cert_0100011001011000110100001011010000110110).T = [false, true, false, false, false, true, true, false, false, true, false, true, true, false, false, false, true, true, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100011001100110001100001011010000110110` (40 bits). -/
def cert_0100011001100110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.app (.var 0) (.app (.var 0) (.app (.var 0) (.lam (.var 1)))))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 3
  binders := 0
  n0 := 0
  trail := [(.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))), (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))))), (.lam (.app (.var 0) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.app (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))) (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))))]

theorem kill_0100011001100110001100001011010000110110 : ¬ HasNormalForm (cert_0100011001100110001100001011010000110110).T :=
  (cert_0100011001100110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100011001100110001100001011010000110110 :
    blcCode (cert_0100011001100110001100001011010000110110).T = [false, true, false, false, false, true, true, false, false, true, true, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0100100001000110001100001011010000110110` (40 bits). -/
def cert_0100100001000110001100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.lam (.var 0)) (.lam (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))))
  kI := 2
  binders := 1
  n0 := 0
  trail := []

theorem kill_0100100001000110001100001011010000110110 : ¬ HasNormalForm (cert_0100100001000110001100001011010000110110).T :=
  (cert_0100100001000110001100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0100100001000110001100001011010000110110 :
    blcCode (cert_0100100001000110001100001011010000110110).T = [false, true, false, false, true, false, false, false, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0101000001100011000100001011010000110110` (40 bits). -/
def cert_0101000001100011000100001011010000110110 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.lam (.app (.var 0) (.lam (.var 1))))) (.lam (.var 0))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kI := 2
  binders := 0
  n0 := 0
  trail := []

theorem kill_0101000001100011000100001011010000110110 : ¬ HasNormalForm (cert_0101000001100011000100001011010000110110).T :=
  (cert_0101000001100011000100001011010000110110).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0101000001100011000100001011010000110110 :
    blcCode (cert_0101000001100011000100001011010000110110).T = [false, true, false, true, false, false, false, false, false, true, true, false, false, false, true, true, false, false, false, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false] := by decide

/-- `0101000110001100001011010000110110000010` (40 bits). -/
def cert_0101000110001100001011010000110110000010 : RatchetCert where
  A := (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))
  W := (.lam (.app (.var 0) (.mvar 0)))
  C0 := (.lam (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1))))))
  kO := 1
  kD := 2
  kB := 1
  T := (.app (.app (.lam (.app (.var 0) (.lam (.var 1)))) (.lam (.app (.app (.var 0) (.var 0)) (.lam (.app (.var 0) (.var 1)))))) (.lam (.lam (.var 0))))
  kI := 1
  binders := 0
  n0 := 0
  trail := [(.lam (.lam (.var 0)))]

theorem kill_0101000110001100001011010000110110000010 : ¬ HasNormalForm (cert_0101000110001100001011010000110110000010).T :=
  (cert_0101000110001100001011010000110110000010).noNormalForm (RatchetCert.valid_of_check (by decide))

theorem wire_0101000110001100001011010000110110000010 :
    blcCode (cert_0101000110001100001011010000110110000010).T = [false, true, false, true, false, false, false, true, true, false, false, false, true, true, false, false, false, false, true, false, true, true, false, true, false, false, false, false, true, true, false, true, true, false, false, false, false, false, true, false] := by decide

end Blc.Certs
