/-
Generated by `cargo run --release --bin certlean` from
tools/cert/ratchet_kills.txt — DO NOT EDIT. Each module carries
the kernel-checked ¬HasNormalForm theorems for one term size;
the emitter is untrusted (see src/bin/certlean.rs).
-/
import Certs.Size32
import Certs.Size34
import Certs.Size35
import Certs.Size36
import Certs.Size37
import Certs.Size38
import Certs.Size39
import Certs.Size40
import Certs.Size41
